// @generated by tools/codegen.sh from spec/schemas/bundle/ — DO NOT EDIT.
//
// Regenerate with `./tools/codegen.sh`. `./tools/codegen.sh --check` asserts
// this file still matches the schemas and runs from tools/selftest.sh.
//
// DR-2: services/notifier and services/approval may both depend on this
// package and on nothing else in common. These are the wire format.
// Rendering is not — no shared template engine, formatter, sanitiser or
// component library. Without that carve-out the first shared formatDate()
// is technically compliant and voids the property.
//
// ONE ASYMMETRY WITH THE RUST OUTPUT, stated rather than papered over. In
// Rust the map behind a fail-safe lookup is a PRIVATE field, so the
// permissive answer is unreachable. A TypeScript interface has no private
// members, so `table.floors[key]` is still writable by a caller who wants
// it. What holds here is weaker: `noUncheckedIndexedAccess` is on, so that
// access is typed `T | undefined` and the caller must handle the absent
// case explicitly — they cannot reach the permissive value by accident,
// only on purpose. The lookup functions below are the supported path.

/**
 * Which of the two acknowledgement duties an enrolled identity may
 * discharge.
 *
 * Hoisted into `$defs` for the same reason `reversibility` was: an inline
 * enum has no name, and a generator inventing one invents a name that
 * drifts.
 *
 * DELIBERATELY NOT ORDERED. A confirmer does not outrank an approver; they
 * are different duties, and DR-9's separation is enforced per action against
 * the proposer rather than by comparing roles.
 * Generated from attesters.schema.json#/$defs/attester_role.
 */
export type AttesterRole = 'approver' | 'confirmer';

/**
 * Ed25519 verification key (RFC 8032), base64. 32 bytes raw; the decoded
 * length is asserted in code, because a base64 string of the wrong length is
 * well-formed JSON and a schema pattern alone would let a truncated key
 * through.
 * Generated from attesters.schema.json#/$defs/ed25519_pub.
 *
 * The schema constrains this to `^[A-Za-z0-9+/]{43}=$`, which is NOT enforced here.
 */
export type Ed25519PublicKey = string;

/**
 * ML-DSA-65 verification key (FIPS 204), base64. 1952 bytes raw. Its size is
 * why hybrid receipts run 13.2 kB against 256 B classical-only — a 53x wire
 * increase that is algorithm-bound and does not improve with a faster
 * library.
 * Generated from attesters.schema.json#/$defs/mldsa65_pub.
 *
 * The schema constrains this to `^[A-Za-z0-9+/]{2603}=$`, which is NOT enforced here.
 */
export type MlDsa65PublicKey = string;

/**
 * A primitive NAME as it appears on the wire.
 *
 * `pq-slh` is declared and NOT implemented. It keeps its own name and fails
 * closed — aliasing it to `pq` would let a verifier report success for a
 * primitive it cannot compute, which is the one thing an unimplemented
 * primitive must never do.
 * Generated from signature.schema.json#/$defs/primitive.
 */
export type PrimitiveName = 'classical' | 'pq' | 'pq-slh';

/**
 * Whether an action class can be undone.
 *
 * Hoisted out of `additionalProperties` into `$defs` so that it has a NAME.
 * An inline enum is a type the generator has to invent a name for, and an
 * invented name is a name that drifts — `floors.schema.json` already
 * declared its values under `$defs.tier` and this file did not, which is a
 * difference with no reason behind it.
 *
 * DELIBERATELY NOT ORDERED. REVERSIBLE and IRREVERSIBLE are two cases, not a
 * scale; a generated `Ord` would invite `max` composition that means nothing
 * here.
 * Generated from reversibility.schema.json#/$defs/reversibility.
 */
export type Reversibility = 'REVERSIBLE' | 'IRREVERSIBLE';

/**
 * Ordered LOW < MEDIUM < HIGH. §8.4 composes with max.
 *
 * A RISK LEVEL IS NOT A RESOURCE TIER. This is a different ladder from
 * `floors.schema.json`'s T0..T3, over a different subject, and §8.4 composes
 * both with max — which is exactly why one type served for both until
 * someone looked. The Rust and TypeScript definitions carried a single
 * `RiskTier` enum whose doc comment cited RK-1's absent-⇒-T3 rule and whose
 * values were LOW/MEDIUM/HIGH, so the fail-safe default was stated in the
 * wrong domain in both. Generated separately, and named separately, for that
 * reason.
 * Generated from risk_functions.schema.json#/$defs/risk.
 */
export type Risk = 'LOW' | 'MEDIUM' | 'HIGH';

/**
 * Risk low to high, from the schema's declared order.
 *
 * TypeScript has no derived ordering, so the ladder is a value and the
 * comparison is a function. §8.4 composes with max, so `max` is what
 * callers need and index arithmetic is what they must not write.
 */
export const RISK_ORDER: readonly Risk[] = [
  'LOW',
  'MEDIUM',
  'HIGH',
];

export function maxRisk(a: Risk, b: Risk): Risk {
  return RISK_ORDER.indexOf(a) >= RISK_ORDER.indexOf(b) ? a : b;
}

/**
 * A suite NAME as it appears on the wire.
 *
 * DELIBERATELY NOT ORDERED. There is no `x-acp-ordered` here and there must
 * not be one: CR-4's floor is satisfied by CONTAINMENT of primitives, not by
 * rank. A generated `Ord` would make `declared >= floor` compile, and that
 * comparison is the downgrade — `ed25519` and `slhdsa128s` are incomparable,
 * not adjacent. The behavioural type is `acp_crypto::Suite`, which carries
 * `satisfies_floor` and `primitives()`; this is the wire name and nothing
 * more.
 *
 * NOT `const`. Listing only the hybrid suite would make a bundle signed
 * under `ed25519` fail SHAPE validation, when the required outcome is a CR-4
 * refusal naming the floor. Unknown names outside this list are refused
 * under CR-1 by the loader, never defaulted to a known suite.
 * Generated from signature.schema.json#/$defs/suite_id.
 */
export type SuiteId = 'ed25519' | 'hybrid-ed25519-mldsa65' | 'slhdsa128s';

/**
 * T0 public/sandbox · T1 internal · T2 production · T3 privileged. Ordered:
 * T0 < T1 < T2 < T3, and §8.4 composes tiers with max, so the ordering is
 * load-bearing rather than cosmetic.
 * Generated from floors.schema.json#/$defs/tier.
 */
export type Tier = 'T0' | 'T1' | 'T2' | 'T3';

/**
 * Tier low to high, from the schema's declared order.
 *
 * TypeScript has no derived ordering, so the ladder is a value and the
 * comparison is a function. §8.4 composes with max, so `max` is what
 * callers need and index arithmetic is what they must not write.
 */
export const TIER_ORDER: readonly Tier[] = [
  'T0',
  'T1',
  'T2',
  'T3',
];

export function maxTier(a: Tier, b: Tier): Tier {
  return TIER_ORDER.indexOf(a) >= TIER_ORDER.indexOf(b) ? a : b;
}

/**
 * `Attester`.
 * Generated from attesters.schema.json#/$defs/attester.
 */
export interface Attester {
  /**
   * approver signs for authorisation; confirmer provides the non-operator
   * positive acknowledgement DR-9 requires for irreversible actions. One
   * person MAY hold both roles in the registry — DR-9 is enforced per action
   * against the proposer, not by role exclusion here.
   */
  readonly role: AttesterRole;
  readonly classical: Ed25519PublicKey;
  readonly pq: MlDsa65PublicKey;
}

/**
 * The lenient projection of Attester: every field optional, every enum
 * degraded to `string`. What a verifier parses. Never make a decision on
 * one — the fail-safe lookups live on the strict type only.
 */
export interface RawAttester {
  readonly role?: string;
  readonly classical?: string;
  readonly pq?: string;
}

/**
 * The approver and confirmer verification keys, and the quorum k.
 *
 * PUBLIC KEYS ONLY. This is not a stylistic constraint — it is the v1.3.14
 * custody fix, and it closed a real hole. Through v1.3.13 the primitives
 * were HMAC-SHA256, so verifying a signature required holding the key that
 * made it: the Executor held every attester key and could therefore MINT ITS
 * OWN QUORUM. INV-1-HIGH did not hold against the very adversary it names,
 * and no protocol test could have found it, because the defect was key
 * CUSTODY rather than control flow. Never reintroduce a symmetric primitive
 * here, not even for tests.
 *
 * PB-KEY: this registry is INSIDE the bundle hash. A `policy_bundle_hash`
 * that does not cover it lets two Executors trusting DIFFERENT attesters
 * agree that they hold the same bundle — which is the encoding-split defect
 * wearing a key registry as a hat.
 *
 * ACK-4 (reference-level, see reference/src/acp_ack.py — not a spec clause):
 * an attester's identity is the one the SIGNATURE covers, never a
 * transmitted `attester_id` field. This registry maps identity to key so
 * that the signature can establish which of these entries signed. It does
 * not authorise anyone to name themselves.
 * Generated from attesters.schema.json.
 */
export interface AttesterRegistry {
  readonly schemaVersion: string;
  /**
   * How many DISTINCT attesters must sign the same canonical hash for a
   * floor-HIGH action. INV-1-HIGH. k=1 is permitted by the schema and is a
   * deployment choice, not a conformance failure — but it collapses the
   * invariant to single-compromise, so a deployment choosing it should say so
   * in its residual risk statement rather than discover it later.
   *
   * DR-9 is enforced separately and is not expressible here: whoever proposed
   * the action can never be among the k.
   */
  readonly quorumK: number;
  /**
   * attester identity -> hybrid public key. Open map (people are
   * deployment-specific), closed entries.
   *
   * PB-DISTINCT (NORMATIVE, and NOT EXPRESSIBLE HERE): no two identities may
   * carry the same public key. `quorum_k` counts DISTINCT KEY HOLDERS; a
   * registry mapping two names onto one key lets the holder of that one
   * private key sign two objects with different nonces, label them with the
   * two names, and satisfy a k=2 quorum alone. INV-1-HIGH broken by a single
   * compromise, reached through the registry rather than through the
   * threshold.
   *
   * JSON Schema cannot state this: `uniqueItems` applies to arrays, and there
   * is no keyword for uniqueness across the VALUES of a map. The rule is
   * therefore enforced by the LOADER, and a loader that does not enforce it is
   * non-conformant however cleanly it validates. Reference implementation:
   * `Bundle.__post_init__` in reference/src/acp_executor.py, which refuses at
   * construction — a bundle whose registry cannot support its own quorum is
   * malformed everywhere it is used, not only on the quorum path. Compare over
   * the full hybrid identity, not the classical half alone; two identities
   * sharing only an ML-DSA key is CR-3 undone at the registry.
   */
  readonly attesters: Readonly<Record<string, Attester>>;
}

/**
 * Look up one entry in AttesterRegistry.attesters.
 *
 * AT-9, PB-6: an identity absent from the signed registry is not an
 * attester. Its signature verifies against no key here and counts toward no
 * quorum, and resolving it to a default would let a name nobody enrolled
 * satisfy INV-1-HIGH. ACK-4: identity is what the SIGNATURE covers, never a
 * transmitted `attester_id` — this map is how a signature is resolved to an
 * enrolled key, not how a name authorises itself.
 *
 * Generated from the schema's `x-acp-absent` rule. It is not restated here.
 */
export type AttesterRegistryLookup =
  | { readonly present: true; readonly value: Attester }
  | { readonly present: false; readonly clause: string; readonly why: string };

export function attesterRegistryLookup(table: AttesterRegistry, key: string): AttesterRegistryLookup {
  const found = table.attesters[key];
  return found === undefined
    ? { present: false, clause: "AT-9, PB-6", why: "an identity absent from the signed registry is not an attester. Its signature verifies against no key here and counts toward no quorum, and resolving it to a default would let a name nobody enrolled satisfy INV-1-HIGH. ACK-4: identity is what the SIGNATURE covers, never a transmitted `attester_id` \u2014 this map is how a signature is resolved to an enrolled key, not how a name authorises itself." }
    : { present: true, value: found };
}

/**
 * The lenient projection of AttesterRegistry: every field optional, every enum
 * degraded to `string`. What a verifier parses. Never make a decision on
 * one — the fail-safe lookups live on the strict type only.
 */
export interface RawAttesterRegistry {
  readonly schemaVersion?: string;
  readonly quorumK?: number;
  readonly attesters?: Readonly<Record<string, RawAttester>>;
}

/**
 * How the bundle signing key is held.
 *
 * CLASSIFIED **T** (trusted as transmitted) AND NOT A CONTROL INPUT. A
 * verifier MUST NOT weight any decision on this object. A bundle asserting
 * its own custody strength is the recurring defect RES-8/RES-9/RES-10 names:
 * a verifier must never accept a derived security value from the party it is
 * verifying. A compromised signer writes this object freely.
 *
 * It is recorded for humans — auditors, operators, and the reviewer named
 * above — and for no other purpose. The real binding is that the verifier is
 * configured out of band with the expected public key.
 * Generated from manifest.schema.json#/$defs/custody.
 */
export interface Custody {
  /**
   * T0 development only; T1 encrypted key on an air-gapped host; T2
   * non-exportable cloud KMS; T3 PKCS#11 HSM. Split custody reports the WEAKER
   * of its two legs, because a claim should never round in the flattering
   * direction.
   *
   * The SAME four values as a resource floor, drawn from `floors.schema.json`
   * so there is one definition of the tier ladder. Note that the two uses are
   * unrelated in meaning: a resource floor says how sensitive a thing is, a
   * custody tier says how a key is held. They share a scale, not a subject.
   */
  readonly tier: Tier;
  readonly classical: CustodyLeg;
  readonly pq: CustodyLeg;
}

/**
 * The lenient projection of Custody: every field optional, every enum
 * degraded to `string`. What a verifier parses. Never make a decision on
 * one — the fail-safe lookups live on the strict type only.
 */
export interface RawCustody {
  readonly tier?: string;
  readonly classical?: RawCustodyLeg;
  readonly pq?: RawCustodyLeg;
}

/**
 * Custody of one primitive. The two legs may differ, and differing is not a
 * weakness: verification is conjunctive (CR-3), so forging requires BOTH
 * signatures and therefore BOTH keys. An attacker must defeat both
 * mechanisms.
 * Generated from manifest.schema.json#/$defs/custody_leg.
 */
export interface CustodyLeg {
  readonly tier: Tier;
  /**
   * Free text naming the concrete mechanism, e.g. "YubiHSM2 slot 3" or
   * "age-encrypted file, offline laptop". Human-readable only.
   */
  readonly mechanism: string;
}

/**
 * The lenient projection of CustodyLeg: every field optional, every enum
 * degraded to `string`. What a verifier parses. Never make a decision on
 * one — the fail-safe lookups live on the strict type only.
 */
export interface RawCustodyLeg {
  readonly tier?: string;
  readonly mechanism?: string;
}

/**
 * Maps each governable resource to its floor tier.
 *
 * RK-1: a resource ABSENT from this file MUST be treated as T3. That rule
 * cannot be expressed in JSON Schema — a schema constrains what is present,
 * never what is missing — so it is carried instead by the `x-acp-absent`
 * annotation on `floors` below, which `tools/codegen.sh` reads to GENERATE
 * the fail-safe direction into `Tier::for_unclassified()` (crates/acp-core)
 * and its TypeScript equivalent. The Python reference spells the same
 * default at `acp_executor.py`. A conformance case asserts it, because a
 * fail-safe default that only exists in a comment is not a control — and
 * stating it only in this prose is what let the Rust and TypeScript versions
 * return HIGH, a RISK LEVEL, where a TIER was required.
 *
 * RES-1 (A-7): the architecture guarantees no runtime component evaluates a
 * resource BELOW its signed floor. It cannot know whether the floor was set
 * correctly. A production database labelled T0 defeats the design with zero
 * attack. Floor maintenance is the highest-leverage governance task in the
 * system and is structurally unprovable — this file is where that risk
 * concentrates.
 * Generated from floors.schema.json.
 */
export interface Floors {
  readonly schemaVersion: string;
  /**
   * resource identifier -> floor tier. Deliberately an open map: resources are
   * deployment-specific. The VALUES are closed.
   */
  readonly floors: Readonly<Record<string, Tier>>;
}

/**
 * Look up one entry in Floors.floors.
 *
 * RK-1: absent means unknown, and unknown is the HIGHEST tier, not the
 * lowest (P-4). Returning T0 or T1 here is the whole class of defect this
 * specification exists to prevent, and it is the direction a lookup
 * returning `Option` invites.
 *
 * Generated from the schema's `x-acp-absent` rule. It is not restated here.
 */
export function floorsLookup(table: Floors, key: string): Tier {
  return table.floors[key] ?? 'T3';
}

/**
 * The lenient projection of Floors: every field optional, every enum
 * degraded to `string`. What a verifier parses. Never make a decision on
 * one — the fail-safe lookups live on the strict type only.
 */
export interface RawFloors {
  readonly schemaVersion?: string;
  readonly floors?: Readonly<Record<string, string>>;
}

/**
 * `Identity`.
 * Generated from manifest.schema.json#/$defs/identity.
 */
export interface Identity {
  /**
   * Stable identifier. Compared byte-for-byte for PB-2; display_name is never
   * used for the comparison because two people can share a display name.
   */
  readonly id: string;
  readonly displayName: string;
}

/**
 * The lenient projection of Identity: every field optional, every enum
 * degraded to `string`. What a verifier parses. Never make a decision on
 * one — the fail-safe lookups live on the strict type only.
 */
export interface RawIdentity {
  readonly id?: string;
  readonly displayName?: string;
}

/**
 * Identity and provenance of one signed policy bundle. PB-5: bundle_epoch is
 * strictly increasing and never reused or decreased. PB-2: author and
 * reviewer identities MUST differ — asserted by the signer, because a schema
 * cannot express a comparison between two of its own fields.
 * Generated from manifest.schema.json.
 */
export interface Manifest {
  /**
   * Version of this manifest schema. Present so a decoder can refuse a bundle
   * it does not fully understand rather than ignoring fields it does not
   * recognise.
   */
  readonly schemaVersion: string;
  /**
   * PB-5. Strictly increasing integer. Never reused, never decreased. The
   * Executor keeps a high-water mark indefinitely (CL-4) — an expiring epoch
   * mark would reopen rollback.
   */
  readonly bundleEpoch: number;
  /**
   * RFC 3339 UTC. Informational: freshness is enforced by expires_at and by
   * the epoch, never by comparing this to a local clock.
   */
  readonly createdAt: string;
  /**
   * Who wrote this bundle. PB-2: MUST differ from reviewer.
   */
  readonly author: Identity;
  /**
   * Who reviewed it. PB-2: MUST differ from author. Two-person integrity on
   * the highest-leverage governance artifact in the system — RES-1 names floor
   * maintenance as exactly that.
   */
  readonly reviewer: Identity;
  /**
   * RFC 3339 UTC. PB-1: the engine MUST refuse to serve an expired bundle. A
   * deployment MAY configure a grace window during which all Decisions are
   * capped at ATTEST — it may not configure one that serves the bundle
   * normally.
   */
  readonly expiresAt: string;
  /**
   * CR-4. The signed floor on signature suites. A receipt or attestation
   * declaring a weaker suite is refused. This is in the signed bundle
   * precisely so a downgrade cannot be negotiated at runtime.
   *
   * It is NOT this bundle's own floor. It floors the suites of downstream
   * receipts and attestations; the floor THIS bundle must clear is configured
   * out of band in the verifier, because a floor a bundle can lower is not a
   * floor (RES-8). Wiring this field in as the bundle's own floor looks like
   * an improvement and is the recurring defect.
   *
   * Drawn from `signature.schema.json` rather than restated, so that one edit
   * to the suite list cannot leave the two spellings disagreeing.
   */
  readonly minSuite: SuiteId;
  readonly custody: Custody;
}

/**
 * The lenient projection of Manifest: every field optional, every enum
 * degraded to `string`. What a verifier parses. Never make a decision on
 * one — the fail-safe lookups live on the strict type only.
 */
export interface RawManifest {
  readonly schemaVersion?: string;
  readonly bundleEpoch?: number;
  readonly createdAt?: string;
  readonly author?: RawIdentity;
  readonly reviewer?: RawIdentity;
  readonly expiresAt?: string;
  readonly minSuite?: string;
  readonly custody?: RawCustody;
}

/**
 * Maps each action class to the parties told when an IRREVERSIBLE action of
 * that class executes BELOW floor-HIGH.
 *
 * WHY THIS FILE EXISTS. Risk is recomputed from the target resource's tier
 * floor; reversibility is a property of the action class. They are
 * orthogonal, so an action can be IRREVERSIBLE and LOW at the same time —
 * and every clause governing irreversible actions lived behind DR-1, which
 * scopes the deferred-release gate to floor-HIGH. Below HIGH the Executor
 * computed the reversibility class and discarded it: the action executed
 * with no notification, no acknowledgement, and no record that a human
 * existed. RV-1's fail-safe default set a value nothing on that path read.
 * Mail exfiltration is exactly this shape — floor an inbox at T1, which is
 * the natural choice because reading mail is routine, and an injected
 * send_email goes out unseen.
 *
 * WHY THE RECIPIENTS ARE HERE AND NOT IN THE NOTIFIER'S CONFIGURATION. A
 * notification service that selects its own audience is certifying its own
 * coverage. That is RES-8 — a verifier must never accept a derived security
 * value from the party it is verifying — and it is the exact shape of the
 * still-open finding T-32, where note.source_path, note.from_canonical and
 * delivered are all classified T. Naming recipients in the signed bundle
 * puts the audience under RK-5 two-person offline control alongside the
 * floors it complements, and makes "who would have found out" a property an
 * auditor reads off signed policy rather than asks the notifier about.
 *
 * ABSENCE FAILS CLOSED, AND JSON SCHEMA CANNOT SAY SO. An action class that
 * is IRREVERSIBLE, graded below HIGH, and absent from this file MUST cause
 * the Executor to refuse the action: a notice with no addressee is not a
 * detection channel, and DR-8's rule — executing while the detection channel
 * is absent is executing unwatched — does not become false because the risk
 * grade is lower. The condition spans three files (this one,
 * reversibility.json, and the risk grading over floors.json), so no schema
 * keyword can express it. The rule is normative in §9.6 DR-13 and its
 * enforcement point is the Executor, as with PB-7 in attesters.schema.json.
 * A normative rule with no enforcement point is a comment.
 *
 * WHAT IS NOT REQUIRED: acknowledgement. DR-9's friction is affordable at
 * floor-HIGH because a human quorum has already been paid for. Below HIGH
 * there is no quorum and the traffic is the bulk of a deployment, so
 * demanding acknowledgement would page a human for routine work at volume —
 * T-26 habituation and AT-7 rubber-stamping, and W2 already recorded that
 * saturating approvers produces assent rather than refusal. DR-13 buys
 * detection, not prevention, and is stated as the weaker guarantee it is.
 *
 * DELIVERY IS NOT A PRECONDITION OF EXECUTION. EO-2 budgets 25 ms p99
 * end-to-end for LOW and MEDIUM decisions and a synchronous confirmed
 * delivery does not fit inside it — two normative requirements that cannot
 * both hold, which is the DR-6 defect class. What DR-13 requires before
 * execution is the durable local commit of the notice. A notice committed
 * and never delivered leaves an audit record and no human; that residual is
 * disclosed as RES-P6, and reconciling committed notices against delivery
 * outcomes is a deployment obligation.
 *
 * A-7 applies here as it does to floors and to reversibility: that a
 * deployment named the RIGHT recipients is conceded unprovable. Deployments
 * SHOULD floor action classes that are both irreversible and externally
 * visible at T2 or above, which moves them onto the deferred path under
 * DR-9; this file is what holds when they have not.
 * Generated from notice_targets.schema.json.
 */
export interface NoticeTargets {
  readonly schemaVersion: string;
  /**
   * action class -> recipient identities. Open map (actions are
   * deployment-specific), and every value is a non-empty set. An empty array
   * is REFUSED rather than treated as 'notify nobody': the two are
   * indistinguishable at run time from an entry that was never written, and
   * the fail-safe reading of both is refusal. Making the empty case invalid
   * here means a deployment that wants no notice channel for a class must say
   * so by floor policy — raise the class to T2+ and let DR-9 govern it —
   * rather than by writing a control that looks configured and does nothing.
   */
  readonly noticeTargets: Readonly<Record<string, readonly string[]>>;
}

/**
 * Look up one entry in NoticeTargets.notice_targets.
 *
 * DR-13: a notice with no addressee is not a detection channel, and DR-8's
 * rule — executing while the detection channel is absent is executing
 * unwatched — does not become false because the risk grade is lower. This is
 * the one absent-rule of the three that is NOT a default value: there is no
 * fail-safe recipient to fall back to, so the fail-safe outcome is that the
 * action does not run. A lookup returning `Option` here would let a caller
 * write `unwrap_or_default()` and execute unwatched with an empty audience.
 *
 * Generated from the schema's `x-acp-absent` rule. It is not restated here.
 */
export type NoticeTargetsLookup =
  | { readonly present: true; readonly value: readonly string[] }
  | { readonly present: false; readonly clause: string; readonly why: string };

export function noticeTargetsLookup(table: NoticeTargets, key: string): NoticeTargetsLookup {
  const found = table.noticeTargets[key];
  return found === undefined
    ? { present: false, clause: "DR-13", why: "a notice with no addressee is not a detection channel, and DR-8's rule \u2014 executing while the detection channel is absent is executing unwatched \u2014 does not become false because the risk grade is lower. This is the one absent-rule of the three that is NOT a default value: there is no fail-safe recipient to fall back to, so the fail-safe outcome is that the action does not run. A lookup returning `Option` here would let a caller write `unwrap_or_default()` and execute unwatched with an empty audience." }
    : { present: true, value: found };
}

/**
 * The lenient projection of NoticeTargets: every field optional, every enum
 * degraded to `string`. What a verifier parses. Never make a decision on
 * one — the fail-safe lookups live on the strict type only.
 */
export interface RawNoticeTargets {
  readonly schemaVersion?: string;
  readonly noticeTargets?: Readonly<Record<string, readonly string[]>>;
}

/**
 * `RaiseClause`.
 * Generated from risk_functions.schema.json#/$defs/raise_clause.
 */
export interface RaiseClause {
  /**
   * An EL-1 expression. EL-1 is deliberately minimal, TOTAL (no expression can
   * fail to evaluate, so there is no error path to fall open through) and
   * monotone.
   *
   * PRECEDENCE IS NORMATIVE: `&&` binds tighter than `||`. That sentence
   * exists because its absence WAS a defect — Z1, found by building two
   * evaluators from the prose alone and running 10,000 differential cases
   * until they disagreed. An implementation that leaves precedence to its host
   * language reproduces the ambiguity.
   */
  readonly if: string;
  readonly then: Risk;
}

/**
 * The lenient projection of RaiseClause: every field optional, every enum
 * degraded to `string`. What a verifier parses. Never make a decision on
 * one — the fail-safe lookups live on the strict type only.
 */
export interface RawRaiseClause {
  readonly if?: string;
  readonly then?: string;
}

/**
 * Maps each action class to whether it can be undone.
 *
 * RV-1: an action ABSENT from this file MUST be treated as IRREVERSIBLE. As
 * with floors, JSON Schema cannot express absence, so the rule is carried by
 * the `x-acp-absent` annotation below and GENERATED into the type: `impl
 * Default for Reversibility` returns `Irreversible` in crates/acp-core, and
 * the lookup on the table returns it directly, so a struct update, a
 * deserialisation gap, or an `Option` a caller unwraps cannot silently
 * produce the permissive value.
 *
 * Why this matters more than it looks: reversibility selects the
 * acknowledgement regime. IRREVERSIBLE at floor-HIGH demands positive
 * acknowledgement from a non-operator (DR-9) — silence is not consent.
 * Getting this entry wrong in the permissive direction converts a held
 * action into a released one.
 *
 * RV-3 is the reason the value is recomputed here and never read from a
 * receipt: a compromised issuer claiming REVERSIBLE otherwise obtains Silent
 * mode. Proven in reference/proofs/binding.dfy as
 * `RV3_TrustedModeAcceptsDowngrade`.
 *
 * A-7 applies here exactly as it does to floors: that a classification is
 * HONEST is conceded unprovable.
 * Generated from reversibility.schema.json.
 */
export interface ReversibilityTable {
  readonly schemaVersion: string;
  /**
   * action class -> reversibility. Open map (actions are deployment-specific),
   * closed values.
   */
  readonly reversibility: Readonly<Record<string, Reversibility>>;
}

/**
 * Look up one entry in ReversibilityTable.reversibility.
 *
 * RV-1: reversibility selects the acknowledgement regime, so the permissive
 * default converts a held action into a released one. An action nobody
 * classified is one nobody thought about, and the fail-safe reading of that
 * is that it cannot be undone.
 *
 * Generated from the schema's `x-acp-absent` rule. It is not restated here.
 */
export function reversibilityTableLookup(table: ReversibilityTable, key: string): Reversibility {
  return table.reversibility[key] ?? 'IRREVERSIBLE';
}

/**
 * The lenient projection of ReversibilityTable: every field optional, every enum
 * degraded to `string`. What a verifier parses. Never make a decision on
 * one — the fail-safe lookups live on the strict type only.
 */
export interface RawReversibilityTable {
  readonly schemaVersion?: string;
  readonly reversibility?: Readonly<Record<string, string>>;
}

/**
 * `RiskFunction`.
 * Generated from risk_functions.schema.json#/$defs/risk_function.
 */
export interface RiskFunction {
  /**
   * Action class this function grades. At most one function per action class —
   * two functions for one class is an ambiguity, not a merge, and the loader
   * refuses it.
   */
  readonly appliesTo: string;
  readonly base: Risk;
  /**
   * Clauses evaluated in order. MONOTONE BY CONSTRUCTION: a clause can only
   * raise the level, never lower it, which is why the field is `raise_to` and
   * there is no `lower_to`. Monotonicity is what makes the Dafny proof that
   * floors dominate raises tractable — a lowering clause would let a crafted
   * parameter walk a HIGH action down to LOW.
   */
  readonly raiseTo: readonly RaiseClause[];
}

/**
 * The lenient projection of RiskFunction: every field optional, every enum
 * degraded to `string`. What a verifier parses. Never make a decision on
 * one — the fail-safe lookups live on the strict type only.
 */
export interface RawRiskFunction {
  readonly appliesTo?: string;
  readonly base?: string;
  readonly raiseTo?: readonly RawRaiseClause[];
}

/**
 * Deterministic functions from a Proposal's parameters and its targets'
 * effective tiers to a risk level.
 *
 * RK-2 exists because static per-action risk is insufficient:
 * `modify_firewall_rule = HIGH` says nothing useful, since risk is a
 * function of PARAMETERS and TARGETS, not action names.
 *
 * THE ABSENT CASE DIFFERS FROM floors AND reversibility. An action with no
 * risk function is REFUSED at §8.4 step 3 — it is NOT graded HIGH. Refusing
 * and grading-HIGH are different behaviours: grading HIGH would route an
 * unknown action into the human quorum, which looks conservative but
 * silently teaches approvers to rubber-stamp things the policy author never
 * considered. P-4: unknown is never LOW, and here it is not HIGH either — it
 * is a refusal.
 *
 * TR-8: these functions are evaluated by the Executor over the INDEPENDENTLY
 * RECEIVED canonical Proposal and the trusted bundle, ignoring every
 * Context-Store raise and ignoring any risk value asserted in the receipt.
 * The recomputed value is what all subsequent attestation requirements key
 * on.
 * Generated from risk_functions.schema.json.
 */
export interface RiskFunctions {
  readonly schemaVersion: string;
  readonly riskFunctions: readonly RiskFunction[];
}

/**
 * Look up one entry in RiskFunctions.risk_functions.
 *
 * 8.4-3: THE ABSENT CASE HERE IS NOT THE ABSENT CASE IN floors OR
 * reversibility. An action with no risk function is REFUSED, not graded
 * HIGH. Grading HIGH would route an unknown action into the human quorum,
 * which looks conservative and is worse: it teaches approvers to
 * rubber-stamp things the policy author never considered (T-26 habituation,
 * AT-7). P-4 says unknown is never LOW; here it is not HIGH either. A lookup
 * returning `Option` would let a caller reach for HIGH as the obvious safe
 * default and get this exactly wrong.
 *
 * Generated from the schema's `x-acp-absent` rule. It is not restated here.
 */
export type RiskFunctionsLookup =
  | { readonly present: true; readonly value: RiskFunction }
  | { readonly present: false; readonly clause: string; readonly why: string };

export function riskFunctionsLookup(table: RiskFunctions, key: string): RiskFunctionsLookup {
  const found = table.riskFunctions.find((item) => item.appliesTo === key);
  return found === undefined
    ? { present: false, clause: "8.4-3", why: "THE ABSENT CASE HERE IS NOT THE ABSENT CASE IN floors OR reversibility. An action with no risk function is REFUSED, not graded HIGH. Grading HIGH would route an unknown action into the human quorum, which looks conservative and is worse: it teaches approvers to rubber-stamp things the policy author never considered (T-26 habituation, AT-7). P-4 says unknown is never LOW; here it is not HIGH either. A lookup returning `Option` would let a caller reach for HIGH as the obvious safe default and get this exactly wrong." }
    : { present: true, value: found };
}

/**
 * The lenient projection of RiskFunctions: every field optional, every enum
 * degraded to `string`. What a verifier parses. Never make a decision on
 * one — the fail-safe lookups live on the strict type only.
 */
export interface RawRiskFunctions {
  readonly schemaVersion?: string;
  readonly riskFunctions?: readonly RawRiskFunction[];
}

/**
 * The `SIGNATURE` file at the bundle root: the declared suite, and one
 * signature value per primitive that suite requires, over SHA-256 of the
 * canonical bundle tree.
 *
 * A CORRECTION IS RECORDED HERE. Until this revision this file was named
 * `bundle.schema.json` and described a *tree index* — `schema_version`, a
 * `members` array of path+digest pairs, and a `signature` object carrying
 * two fixed base64 fields named `classical` and `pq`. None of that artifact
 * exists. §8.2's file listing contains no index file; the covered set is
 * established by the CANONICAL WALK (`walk_bundle`, in both
 * implementations), which is what makes "the tree" a fact rather than a
 * convention. And PB-8, added in v1.3.15 when the offline signer turned the
 * format from a diagram into bytes, specifies the file as a suite plus ONE
 * VALUE PER PRIMITIVE — a map keyed by primitive name, hex-encoded — which
 * is not the fixed pair the old schema declared.
 *
 * So the normative source held two descriptions of one object, and they
 * disagreed: the encoding-split defect arriving inside the document that
 * exists to prevent it. It survived because NOTHING READ THE SCHEMAS. They
 * were normative and unexecuted, and the first consumer — `tools/codegen.sh`
 * — found this on its first run. That is the same shape as `sim/bundle.py`
 * silently dropping three fields from a hash for several releases: a
 * load-bearing artifact with no gate line.
 *
 * WHY THE MEMBERS INDEX IS NOT COMING BACK. The old rationale was real —
 * without an explicit list, a verifier that skipped a file and a signer that
 * included it compute different hashes and neither can tell which is wrong.
 * The adopted answer is to make the WALK normative rather than to ship a
 * list: it refuses symlinks, refuses unrecognised file types, and orders
 * byte-wise, so two conformant implementations enumerate the same set. A
 * committed index would be a second statement of the same fact, and this
 * file exists because of what happens to the second statement.
 * Generated from signature.schema.json.
 */
export interface SignatureEnvelope {
  /**
   * The suite this signature was produced under. PB-8: it MUST be inside the
   * tree hash. Outside it, an attacker relabels a hybrid bundle as classical,
   * the verifier obligingly requires one primitive, and the CR-3 downgrade
   * costs nothing.
   */
  readonly suite: SuiteId;
  /**
   * primitive name -> signature value, lowercase hex.
   *
   * CR-3, CONJUNCTIVE: the values present MUST be exactly those the declared
   * suite requires, and every one of them MUST verify. Not "at least": a value
   * for a primitive the suite does not declare is as much a refusal as a
   * missing one, because an `any`-shaped check lets an attacker strip the
   * post-quantum leg, present a genuine classical signature, and be accepted.
   *
   * Hex rather than base64, matching what both implementations write.
   * Per-primitive lengths (Ed25519 64 bytes, ML-DSA-65 3309) are asserted in
   * code and not here: `parts` is keyed by primitive, so no single value
   * pattern can express a length that depends on its own key.
   */
  readonly parts: Readonly<Record<string, string>>;
}

/**
 * Look up one entry in SignatureEnvelope.parts.
 *
 * CR-3, PB-8: a primitive the declared suite requires and this file does not
 * carry is a stripped leg, and a stripped leg is the downgrade the hybrid
 * suite exists to prevent. Absent is refused, never treated as 'not
 * applicable'.
 *
 * Generated from the schema's `x-acp-absent` rule. It is not restated here.
 */
export type SignatureEnvelopeLookup =
  | { readonly present: true; readonly value: string }
  | { readonly present: false; readonly clause: string; readonly why: string };

export function signatureEnvelopeLookup(table: SignatureEnvelope, key: string): SignatureEnvelopeLookup {
  const found = table.parts[key];
  return found === undefined
    ? { present: false, clause: "CR-3, PB-8", why: "a primitive the declared suite requires and this file does not carry is a stripped leg, and a stripped leg is the downgrade the hybrid suite exists to prevent. Absent is refused, never treated as 'not applicable'." }
    : { present: true, value: found };
}

/**
 * The lenient projection of SignatureEnvelope: every field optional, every enum
 * degraded to `string`. What a verifier parses. Never make a decision on
 * one — the fail-safe lookups live on the strict type only.
 */
export interface RawSignatureEnvelope {
  readonly suite?: string;
  readonly parts?: Readonly<Record<string, string>>;
}
