#!/usr/bin/env bash
# sign-release.sh — regenerate MANIFEST.sha256 and sign it with the OFFLINE
# release key. Run on the signing host, not on a build server.
#
# The private key is never generated by tooling that touched the dossier and
# never lives in this repository. RK-5 discipline applies to the release key
# for the same reason it applies to the policy bundle: a signature is only
# worth the custody of the key behind it.
#
#   ./sign-release.sh keygen             # once, on the offline host
#   ./sign-release.sh sign  ~/acp.key  # regenerate manifest + sign
set -euo pipefail
cd "$(dirname "$0")"

# Coverage is three allowlists and no deny-list. Each axis independently
# refuses to admit something unrecognised:
#
#   1. roots     -- only these directories are eligible at all
#   2. tracked   -- only files git tracks; build outputs are excluded because
#                   they are gitignored, not because a list names them
#   3. extension -- only these types, plus explicit filenames
#
# A deny-list fails open: the next thing someone adds is covered by default.
# That is how the previous blanket `find .` would have swept private/ and a
# stray .venv into a public manifest, publishing their filenames and hashes.
#
# ROOTS is the CURRENT tree. The polyglot layout replaces it with:
#   spec dossier reference crates services packages orchestrator sim deploy tools
ROOTS="artifacts sim"
EXTS="md py rs ts json cddl dfy toml yml yaml lock txt sh pub"
NAMED="LICENSE Dockerfile .gitignore"

covered_files() {
  # Universe: every tracked file at the repository root, plus every tracked
  # file under a signed root directory. Enumerating root files by name was
  # tried and rejected -- it silently dropped the eleven numbered dossier
  # documents and both tools. Depth-1 plus an extension allowlist keeps the
  # fail-safe property without a list that rots every time a document is added.
  { git ls-files | grep -v '/'
    for r in $ROOTS; do
      if [ -d "$r" ]; then git ls-files -- "$r"; fi
    done
  } | grep -vE '^MANIFEST\.sha256(\.sig)?$' | sort -u
}

# Halt if any covered file has a type we do not recognise. A new file type must
# stop the release, not be silently signed and not be silently skipped.
assert_all_recognised() {
  bad=""
  for f in $(covered_files); do
    base=${f##*/}
    ext=""
    case "$base" in *.*) ext=${base##*.} ;; esac
    case " $NAMED " in *" $base "*) continue ;; esac
    case " $EXTS " in *" $ext "*) continue ;; esac
    bad="$bad $f"
  done
  if [ -n "$bad" ]; then
    echo "unrecognised file type under a signed root:" >&2
    for f in $bad; do echo "    $f" >&2; done
    echo "  add its extension to EXTS, or its name to NAMED, or exclude it." >&2
    exit 4
  fi
}

assert_roots_present() {
  for r in $ROOTS; do
    [ -d "$r" ] || { echo "missing signed root: $r" >&2; exit 3; }
  done
}

case "${1:-}" in
keygen)
  python3 - <<'PY'
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives import serialization as ser
import hashlib, os
sk = Ed25519PrivateKey.generate()
priv = sk.private_bytes(ser.Encoding.PEM, ser.PrivateFormat.PKCS8,
                        ser.NoEncryption())
pub = sk.public_key().public_bytes(ser.Encoding.PEM,
                                   ser.PublicFormat.SubjectPublicKeyInfo)
path = os.path.expanduser("~/acp-release.key")
with open(path, "wb") as f: f.write(priv)
os.chmod(path, 0o600)
open("release-key.pub", "wb").write(pub)
raw = sk.public_key().public_bytes(ser.Encoding.Raw, ser.PublicFormat.Raw)
print(f"private key : {path}  (move to offline media, chmod 600)")
print(f"public key  : release-key.pub  (ships with the dossier)")
print(f"fingerprint : SHA256:{hashlib.sha256(raw).hexdigest()[:32]}")
print("\nPublish that fingerprint out of band -- on the repository README, in\n"
      "the talk, in the review brief. A public key shipped only inside the\n"
      "package it authenticates proves nothing.")
PY
  ;;
list)
  # What `sign` would cover, without needing the offline key. This is what
  # makes the coverage model testable at all: selftest.sh runs it, sign does not.
  assert_roots_present
  assert_all_recognised
  covered_files
  ;;

sign)
  KEY="${2:?usage: ./sign-release.sh sign /path/to/acp-release.key}"
  assert_roots_present
  assert_all_recognised
  covered_files | xargs sha256sum > MANIFEST.sha256
  python3 - "$KEY" <<'PY'
import sys
from cryptography.hazmat.primitives.serialization import load_pem_private_key
sk = load_pem_private_key(open(sys.argv[1], "rb").read(), password=None)
open("MANIFEST.sha256.sig", "wb").write(sk.sign(open("MANIFEST.sha256", "rb").read()))
print("signed -> MANIFEST.sha256.sig")
PY
  echo "files covered: $(wc -l < MANIFEST.sha256)"
  ;;
*)
  echo "usage: $0 {keygen|sign <keyfile>}"; exit 2 ;;
esac
