#!/usr/bin/env bash
# sign-release.sh — regenerate MANIFEST.sha256 and sign it with the OFFLINE
# release key. Run on the signing host, not on a build server.
#
# The private key is never generated by tooling that touched the dossier and
# never lives in this repository. RK-5 discipline applies to the release key
# for the same reason it applies to the policy bundle: a signature is only
# worth the custody of the key behind it.
#
#   ./sign-release.sh keygen             # once, on the offline host
#   ./sign-release.sh sign  ~/acp.key  # regenerate manifest + sign
set -euo pipefail
cd "$(dirname "$0")"

case "${1:-}" in
keygen)
  python3 - <<'PY'
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives import serialization as ser
import hashlib, os
sk = Ed25519PrivateKey.generate()
priv = sk.private_bytes(ser.Encoding.PEM, ser.PrivateFormat.PKCS8,
                        ser.NoEncryption())
pub = sk.public_key().public_bytes(ser.Encoding.PEM,
                                   ser.PublicFormat.SubjectPublicKeyInfo)
path = os.path.expanduser("~/acp-release.key")
with open(path, "wb") as f: f.write(priv)
os.chmod(path, 0o600)
open("release-key.pub", "wb").write(pub)
raw = sk.public_key().public_bytes(ser.Encoding.Raw, ser.PublicFormat.Raw)
print(f"private key : {path}  (move to offline media, chmod 600)")
print(f"public key  : release-key.pub  (ships with the dossier)")
print(f"fingerprint : SHA256:{hashlib.sha256(raw).hexdigest()[:32]}")
print("\nPublish that fingerprint out of band -- on the repository README, in\n"
      "the talk, in the review brief. A public key shipped only inside the\n"
      "package it authenticates proves nothing.")
PY
  ;;
sign)
  KEY="${2:?usage: ./sign-release.sh sign /path/to/acp-release.key}"
  find . -type f \( -name '*.md' -o -name '*.py' -o -name '*.dfy' -o -name '*.txt' \
       -o -name '*.sh' -o -name '*.pub' \) ! -name 'MANIFEST.sha256' \
       | sort | xargs sha256sum > MANIFEST.sha256
  python3 - "$KEY" <<'PY'
import sys
from cryptography.hazmat.primitives.serialization import load_pem_private_key
sk = load_pem_private_key(open(sys.argv[1], "rb").read(), password=None)
open("MANIFEST.sha256.sig", "wb").write(sk.sign(open("MANIFEST.sha256", "rb").read()))
print("signed -> MANIFEST.sha256.sig")
PY
  echo "files covered: $(wc -l < MANIFEST.sha256)"
  ;;
*)
  echo "usage: $0 {keygen|sign <keyfile>}"; exit 2 ;;
esac
