// @generated by tools/codegen.sh from spec/schemas/bundle/ — DO NOT EDIT.
//
// Regenerate with `./tools/codegen.sh`. `./tools/codegen.sh --check` asserts
// this file still matches the schemas and runs from tools/selftest.sh.
//
// Editing this file by hand creates a second definition of an object the
// specification already defines, which is the encoding-split defect at the
// source level. The drift check exists to catch exactly that edit.
#![allow(rustdoc::broken_intra_doc_links)]

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

/// A lookup that missed, in a table whose absent case is a REFUSAL rather
/// than a default value.
///
/// Returned instead of `Option` so that the fail-safe outcome is the one a
/// caller has to handle. `Option::unwrap_or` is a single idiom away from
/// the permissive answer; a `Result` carrying the clause that governs the
/// refusal is not.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AbsentFromSignedPolicy {
    /// The signed table that was consulted.
    pub table: &'static str,
    /// The clause that says an absent entry is a refusal.
    pub clause: &'static str,
    /// Why absence fails closed here, in the schema's own words.
    pub why: &'static str,
}

/// Why a lenient `Raw*` value could not be promoted to its strict form.
///
/// The two layers exist because a verifier and a service want different
/// things from one schema. A service wants the whole object or nothing. A
/// verifier wants to know WHICH field was missing, because its refusals are
/// distinguishable by design — an absent `quorum_k` is `QuorumInvalid` and
/// not `Malformed`, and an operator paged at 03:00 needs the difference.
/// Collapsing every absence into one parse error would lose that, and the
/// cross-language differential asserts the refusal NAME.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SchemaDefect {
    pub type_name: &'static str,
    pub field: &'static str,
    pub kind: DefectKind,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DefectKind {
    /// The schema requires this field and it is not present.
    Missing,
    /// A `const` field carries a value the schema does not allow. Refused
    /// rather than ignored: the field exists so a decoder can reject a
    /// document it does not fully understand.
    UnexpectedConst,
    /// An integer below the schema's `minimum`.
    BelowMinimum,
    /// Two items in a keyed array claim the same key. Refused rather than
    /// merged or last-wins: two entries for one key is an ambiguity, and
    /// picking one is a guess.
    DuplicateKey,
}

/// Which of the two acknowledgement duties an enrolled identity may
/// discharge.
///
/// Hoisted into `$defs` for the same reason `reversibility` was: an inline
/// enum has no name, and a generator inventing one invents a name that
/// drifts.
///
/// DELIBERATELY NOT ORDERED. A confirmer does not outrank an approver; they
/// are different duties, and DR-9's separation is enforced per action against
/// the proposer rather than by comparing roles.
/// Generated from attesters.schema.json#/$defs/attester_role.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
// NOT ordered. The schema does not declare x-acp-ordered, and a derived
// `Ord` on a set with no order is a comparison that compiles and means
// nothing — for SuiteId it would make `declared >= floor` compile, and
// that comparison is the CR-4 downgrade.
pub enum AttesterRole {
    #[serde(rename = "approver")]
    Approver,
    #[serde(rename = "confirmer")]
    Confirmer,
}

impl AttesterRole {
    /// The wire spelling, which is what a hash covers.
    pub const fn as_wire(self) -> &'static str {
        match self {
            AttesterRole::Approver => "approver",
            AttesterRole::Confirmer => "confirmer",
        }
    }

    /// Parse a wire spelling. An unknown value is `None` and MUST be
    /// refused by the caller, never resolved to a known one.
    pub fn from_wire(s: &str) -> Option<Self> {
        match s {
            "approver" => Some(AttesterRole::Approver),
            "confirmer" => Some(AttesterRole::Confirmer),
            _ => None,
        }
    }
}

/// Ed25519 verification key (RFC 8032), base64. 32 bytes raw; the decoded
/// length is asserted in code, because a base64 string of the wrong length is
/// well-formed JSON and a schema pattern alone would let a truncated key
/// through.
/// Generated from attesters.schema.json#/$defs/ed25519_pub.
///
/// The schema constrains this to `^[A-Za-z0-9+/]{43}=$`. That pattern is NOT
/// enforced here — see the module note on what codegen does not validate.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(transparent)]
pub struct Ed25519PublicKey(pub String);

/// ML-DSA-65 verification key (FIPS 204), base64. 1952 bytes raw. Its size is
/// why hybrid receipts run 13.2 kB against 256 B classical-only — a 53x wire
/// increase that is algorithm-bound and does not improve with a faster
/// library.
/// Generated from attesters.schema.json#/$defs/mldsa65_pub.
///
/// The schema constrains this to `^[A-Za-z0-9+/]{2603}=$`. That pattern is NOT
/// enforced here — see the module note on what codegen does not validate.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(transparent)]
pub struct MlDsa65PublicKey(pub String);

/// A primitive NAME as it appears on the wire.
///
/// `pq-slh` is declared and NOT implemented. It keeps its own name and fails
/// closed — aliasing it to `pq` would let a verifier report success for a
/// primitive it cannot compute, which is the one thing an unimplemented
/// primitive must never do.
/// Generated from signature.schema.json#/$defs/primitive.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
// NOT ordered. The schema does not declare x-acp-ordered, and a derived
// `Ord` on a set with no order is a comparison that compiles and means
// nothing — for SuiteId it would make `declared >= floor` compile, and
// that comparison is the CR-4 downgrade.
pub enum PrimitiveName {
    #[serde(rename = "classical")]
    Classical,
    #[serde(rename = "pq")]
    Pq,
    #[serde(rename = "pq-slh")]
    PqSlh,
}

impl PrimitiveName {
    /// The wire spelling, which is what a hash covers.
    pub const fn as_wire(self) -> &'static str {
        match self {
            PrimitiveName::Classical => "classical",
            PrimitiveName::Pq => "pq",
            PrimitiveName::PqSlh => "pq-slh",
        }
    }

    /// Parse a wire spelling. An unknown value is `None` and MUST be
    /// refused by the caller, never resolved to a known one.
    pub fn from_wire(s: &str) -> Option<Self> {
        match s {
            "classical" => Some(PrimitiveName::Classical),
            "pq" => Some(PrimitiveName::Pq),
            "pq-slh" => Some(PrimitiveName::PqSlh),
            _ => None,
        }
    }
}

/// Whether an action class can be undone.
///
/// Hoisted out of `additionalProperties` into `$defs` so that it has a NAME.
/// An inline enum is a type the generator has to invent a name for, and an
/// invented name is a name that drifts — `floors.schema.json` already
/// declared its values under `$defs.tier` and this file did not, which is a
/// difference with no reason behind it.
///
/// DELIBERATELY NOT ORDERED. REVERSIBLE and IRREVERSIBLE are two cases, not a
/// scale; a generated `Ord` would invite `max` composition that means nothing
/// here.
/// Generated from reversibility.schema.json#/$defs/reversibility.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
// NOT ordered. The schema does not declare x-acp-ordered, and a derived
// `Ord` on a set with no order is a comparison that compiles and means
// nothing — for SuiteId it would make `declared >= floor` compile, and
// that comparison is the CR-4 downgrade.
pub enum Reversibility {
    #[serde(rename = "REVERSIBLE")]
    Reversible,
    #[serde(rename = "IRREVERSIBLE")]
    Irreversible,
}

impl Reversibility {
    /// The wire spelling, which is what a hash covers.
    pub const fn as_wire(self) -> &'static str {
        match self {
            Reversibility::Reversible => "REVERSIBLE",
            Reversibility::Irreversible => "IRREVERSIBLE",
        }
    }

    /// Parse a wire spelling. An unknown value is `None` and MUST be
    /// refused by the caller, never resolved to a known one.
    pub fn from_wire(s: &str) -> Option<Self> {
        match s {
            "REVERSIBLE" => Some(Reversibility::Reversible),
            "IRREVERSIBLE" => Some(Reversibility::Irreversible),
            _ => None,
        }
    }
}

/// Ordered LOW < MEDIUM < HIGH. §8.4 composes with max.
///
/// A RISK LEVEL IS NOT A RESOURCE TIER. This is a different ladder from
/// `floors.schema.json`'s T0..T3, over a different subject, and §8.4 composes
/// both with max — which is exactly why one type served for both until
/// someone looked. The Rust and TypeScript definitions carried a single
/// `RiskTier` enum whose doc comment cited RK-1's absent-⇒-T3 rule and whose
/// values were LOW/MEDIUM/HIGH, so the fail-safe default was stated in the
/// wrong domain in both. Generated separately, and named separately, for that
/// reason.
/// Generated from risk_functions.schema.json#/$defs/risk.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
// Ordered because the schema declares x-acp-ordered: the variants are
// written low to high, so the derived Ord composes with `max` the way
// §8.4 requires. Reordering the variants changes the meaning of every
// comparison in the system.
pub enum Risk {
    #[serde(rename = "LOW")]
    Low,
    #[serde(rename = "MEDIUM")]
    Medium,
    #[serde(rename = "HIGH")]
    High,
}

impl Risk {
    /// The wire spelling, which is what a hash covers.
    pub const fn as_wire(self) -> &'static str {
        match self {
            Risk::Low => "LOW",
            Risk::Medium => "MEDIUM",
            Risk::High => "HIGH",
        }
    }

    /// Parse a wire spelling. An unknown value is `None` and MUST be
    /// refused by the caller, never resolved to a known one.
    pub fn from_wire(s: &str) -> Option<Self> {
        match s {
            "LOW" => Some(Risk::Low),
            "MEDIUM" => Some(Risk::Medium),
            "HIGH" => Some(Risk::High),
            _ => None,
        }
    }
}

/// A suite NAME as it appears on the wire.
///
/// DELIBERATELY NOT ORDERED. There is no `x-acp-ordered` here and there must
/// not be one: CR-4's floor is satisfied by CONTAINMENT of primitives, not by
/// rank. A generated `Ord` would make `declared >= floor` compile, and that
/// comparison is the downgrade — `ed25519` and `slhdsa128s` are incomparable,
/// not adjacent. The behavioural type is `acp_crypto::Suite`, which carries
/// `satisfies_floor` and `primitives()`; this is the wire name and nothing
/// more.
///
/// NOT `const`. Listing only the hybrid suite would make a bundle signed
/// under `ed25519` fail SHAPE validation, when the required outcome is a CR-4
/// refusal naming the floor. Unknown names outside this list are refused
/// under CR-1 by the loader, never defaulted to a known suite.
/// Generated from signature.schema.json#/$defs/suite_id.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
// NOT ordered. The schema does not declare x-acp-ordered, and a derived
// `Ord` on a set with no order is a comparison that compiles and means
// nothing — for SuiteId it would make `declared >= floor` compile, and
// that comparison is the CR-4 downgrade.
pub enum SuiteId {
    #[serde(rename = "ed25519")]
    Ed25519,
    #[serde(rename = "hybrid-ed25519-mldsa65")]
    HybridEd25519Mldsa65,
    #[serde(rename = "slhdsa128s")]
    Slhdsa128s,
}

impl SuiteId {
    /// The wire spelling, which is what a hash covers.
    pub const fn as_wire(self) -> &'static str {
        match self {
            SuiteId::Ed25519 => "ed25519",
            SuiteId::HybridEd25519Mldsa65 => "hybrid-ed25519-mldsa65",
            SuiteId::Slhdsa128s => "slhdsa128s",
        }
    }

    /// Parse a wire spelling. An unknown value is `None` and MUST be
    /// refused by the caller, never resolved to a known one.
    pub fn from_wire(s: &str) -> Option<Self> {
        match s {
            "ed25519" => Some(SuiteId::Ed25519),
            "hybrid-ed25519-mldsa65" => Some(SuiteId::HybridEd25519Mldsa65),
            "slhdsa128s" => Some(SuiteId::Slhdsa128s),
            _ => None,
        }
    }
}

/// T0 public/sandbox · T1 internal · T2 production · T3 privileged. Ordered:
/// T0 < T1 < T2 < T3, and §8.4 composes tiers with max, so the ordering is
/// load-bearing rather than cosmetic.
/// Generated from floors.schema.json#/$defs/tier.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
// Ordered because the schema declares x-acp-ordered: the variants are
// written low to high, so the derived Ord composes with `max` the way
// §8.4 requires. Reordering the variants changes the meaning of every
// comparison in the system.
pub enum Tier {
    #[serde(rename = "T0")]
    T0,
    #[serde(rename = "T1")]
    T1,
    #[serde(rename = "T2")]
    T2,
    #[serde(rename = "T3")]
    T3,
}

impl Tier {
    /// The wire spelling, which is what a hash covers.
    pub const fn as_wire(self) -> &'static str {
        match self {
            Tier::T0 => "T0",
            Tier::T1 => "T1",
            Tier::T2 => "T2",
            Tier::T3 => "T3",
        }
    }

    /// Parse a wire spelling. An unknown value is `None` and MUST be
    /// refused by the caller, never resolved to a known one.
    pub fn from_wire(s: &str) -> Option<Self> {
        match s {
            "T0" => Some(Tier::T0),
            "T1" => Some(Tier::T1),
            "T2" => Some(Tier::T2),
            "T3" => Some(Tier::T3),
            _ => None,
        }
    }
}

/// `Attester`.
/// Generated from attesters.schema.json#/$defs/attester.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Attester {
    /// approver signs for authorisation; confirmer provides the non-operator
    /// positive acknowledgement DR-9 requires for irreversible actions. One
    /// person MAY hold both roles in the registry — DR-9 is enforced per action
    /// against the proposer, not by role exclusion here.
    pub role: AttesterRole,
    pub classical: Ed25519PublicKey,
    pub pq: MlDsa65PublicKey,
}

/// The lenient projection of [`Attester`].
///
/// Every field optional, every enum degraded to `String`. This is what a
/// VERIFIER parses, and the leniency is deliberate: reading five named
/// security fields fail-closed is field access, and a strict parse would
/// collapse every distinct refusal into one `Malformed`. It also means a
/// field no verifier reads cannot cause a refusal by being the wrong shape.
///
/// **Never make a decision on a `Raw*` value.** Promote it with `try_from`,
/// or read one named field and apply the check that governs it. The
/// fail-safe accessors live on the strict type only, so a `Raw*` cannot
/// answer a policy question at all.
#[derive(Debug, Clone, PartialEq, Eq, Default, Deserialize)]
pub struct RawAttester {
    pub role: Option<String>,
    pub classical: Option<String>,
    pub pq: Option<String>,
}

/// The approver and confirmer verification keys, and the quorum k.
///
/// PUBLIC KEYS ONLY. This is not a stylistic constraint — it is the v1.3.14
/// custody fix, and it closed a real hole. Through v1.3.13 the primitives
/// were HMAC-SHA256, so verifying a signature required holding the key that
/// made it: the Executor held every attester key and could therefore MINT ITS
/// OWN QUORUM. INV-1-HIGH did not hold against the very adversary it names,
/// and no protocol test could have found it, because the defect was key
/// CUSTODY rather than control flow. Never reintroduce a symmetric primitive
/// here, not even for tests.
///
/// PB-KEY: this registry is INSIDE the bundle hash. A `policy_bundle_hash`
/// that does not cover it lets two Executors trusting DIFFERENT attesters
/// agree that they hold the same bundle — which is the encoding-split defect
/// wearing a key registry as a hat.
///
/// ACK-4 (reference-level, see reference/src/acp_ack.py — not a spec clause):
/// an attester's identity is the one the SIGNATURE covers, never a
/// transmitted `attester_id` field. This registry maps identity to key so
/// that the signature can establish which of these entries signed. It does
/// not authorise anyone to name themselves.
/// Generated from attesters.schema.json.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AttesterRegistry {
    pub schema_version: String,
    /// How many DISTINCT attesters must sign the same canonical hash for a
    /// floor-HIGH action. INV-1-HIGH. k=1 is permitted by the schema and is a
    /// deployment choice, not a conformance failure — but it collapses the
    /// invariant to single-compromise, so a deployment choosing it should say so
    /// in its residual risk statement rather than discover it later.
    ///
    /// DR-9 is enforced separately and is not expressible here: whoever proposed
    /// the action can never be among the k.
    pub quorum_k: u64,
    /// attester identity -> hybrid public key. Open map (people are
    /// deployment-specific), closed entries.
    ///
    /// PB-DISTINCT (NORMATIVE, and NOT EXPRESSIBLE HERE): no two identities may
    /// carry the same public key. `quorum_k` counts DISTINCT KEY HOLDERS; a
    /// registry mapping two names onto one key lets the holder of that one
    /// private key sign two objects with different nonces, label them with the
    /// two names, and satisfy a k=2 quorum alone. INV-1-HIGH broken by a single
    /// compromise, reached through the registry rather than through the
    /// threshold.
    ///
    /// JSON Schema cannot state this: `uniqueItems` applies to arrays, and there
    /// is no keyword for uniqueness across the VALUES of a map. The rule is
    /// therefore enforced by the LOADER, and a loader that does not enforce it is
    /// non-conformant however cleanly it validates. Reference implementation:
    /// `Bundle.__post_init__` in reference/src/acp_executor.py, which refuses at
    /// construction — a bundle whose registry cannot support its own quorum is
    /// malformed everywhere it is used, not only on the quorum path. Compare over
    /// the full hybrid identity, not the classical half alone; two identities
    /// sharing only an ML-DSA key is CR-3 undone at the registry.
    /// PRIVATE, deliberately. Reached through the accessor below, which
    /// carries the fail-safe absent rule the schema declares. A public
    /// map is a `.get()` away from an `Option` and an `Option` is one
    /// `unwrap_or` away from the permissive default.
    attesters: BTreeMap<String, Attester>,
}

impl AttesterRegistry {
    /// The only `schema_version` this build understands.
    pub const SCHEMA_VERSION: &'static str = "1";

    /// Look up one entry in `attesters`.
    ///
    /// AT-9, PB-6: an identity absent from the signed registry is not an
    /// attester. Its signature verifies against no key here and counts toward no
    /// quorum, and resolving it to a default would let a name nobody enrolled
    /// satisfy INV-1-HIGH. ACK-4: identity is what the SIGNATURE covers, never a
    /// transmitted `attester_id` — this map is how a signature is resolved to an
    /// enrolled key, not how a name authorises itself.
    ///
    /// Generated from the schema's `x-acp-absent` rule. It is not restated
    /// here, and editing it there changes this.
    pub fn get(&self, key: &str) -> Result<&Attester, AbsentFromSignedPolicy> {
        self.attesters.get(key).ok_or(AbsentFromSignedPolicy {
            table: "attesters",
            clause: "AT-9, PB-6",
            why: "an identity absent from the signed registry is not an attester. Its signature verifies against no key here and counts toward no quorum, and resolving it to a default would let a name nobody enrolled satisfy INV-1-HIGH. ACK-4: identity is what the SIGNATURE covers, never a transmitted `attester_id` — this map is how a signature is resolved to an enrolled key, not how a name authorises itself.",
        })
    }

    /// Every entry, for callers that enumerate rather than look up — an
    /// auditor listing signed policy, not a decision path.
    pub fn entries(&self) -> impl Iterator<Item = (&String, &Attester)> {
        self.attesters.iter()
    }
}

/// The lenient projection of [`AttesterRegistry`].
///
/// Every field optional, every enum degraded to `String`. This is what a
/// VERIFIER parses, and the leniency is deliberate: reading five named
/// security fields fail-closed is field access, and a strict parse would
/// collapse every distinct refusal into one `Malformed`. It also means a
/// field no verifier reads cannot cause a refusal by being the wrong shape.
///
/// **Never make a decision on a `Raw*` value.** Promote it with `try_from`,
/// or read one named field and apply the check that governs it. The
/// fail-safe accessors live on the strict type only, so a `Raw*` cannot
/// answer a policy question at all.
#[derive(Debug, Clone, PartialEq, Eq, Default, Deserialize)]
pub struct RawAttesterRegistry {
    pub schema_version: Option<String>,
    pub quorum_k: Option<u64>,
    pub attesters: Option<BTreeMap<String, RawAttester>>,
}

/// How the bundle signing key is held.
///
/// CLASSIFIED **T** (trusted as transmitted) AND NOT A CONTROL INPUT. A
/// verifier MUST NOT weight any decision on this object. A bundle asserting
/// its own custody strength is the recurring defect RES-8/RES-9/RES-10 names:
/// a verifier must never accept a derived security value from the party it is
/// verifying. A compromised signer writes this object freely.
///
/// It is recorded for humans — auditors, operators, and the reviewer named
/// above — and for no other purpose. The real binding is that the verifier is
/// configured out of band with the expected public key.
/// Generated from manifest.schema.json#/$defs/custody.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Custody {
    /// T0 development only; T1 encrypted key on an air-gapped host; T2
    /// non-exportable cloud KMS; T3 PKCS#11 HSM. Split custody reports the WEAKER
    /// of its two legs, because a claim should never round in the flattering
    /// direction.
    ///
    /// The SAME four values as a resource floor, drawn from `floors.schema.json`
    /// so there is one definition of the tier ladder. Note that the two uses are
    /// unrelated in meaning: a resource floor says how sensitive a thing is, a
    /// custody tier says how a key is held. They share a scale, not a subject.
    pub tier: Tier,
    pub classical: CustodyLeg,
    pub pq: CustodyLeg,
}

/// The lenient projection of [`Custody`].
///
/// Every field optional, every enum degraded to `String`. This is what a
/// VERIFIER parses, and the leniency is deliberate: reading five named
/// security fields fail-closed is field access, and a strict parse would
/// collapse every distinct refusal into one `Malformed`. It also means a
/// field no verifier reads cannot cause a refusal by being the wrong shape.
///
/// **Never make a decision on a `Raw*` value.** Promote it with `try_from`,
/// or read one named field and apply the check that governs it. The
/// fail-safe accessors live on the strict type only, so a `Raw*` cannot
/// answer a policy question at all.
#[derive(Debug, Clone, PartialEq, Eq, Default, Deserialize)]
pub struct RawCustody {
    pub tier: Option<String>,
    pub classical: Option<RawCustodyLeg>,
    pub pq: Option<RawCustodyLeg>,
}

/// Custody of one primitive. The two legs may differ, and differing is not a
/// weakness: verification is conjunctive (CR-3), so forging requires BOTH
/// signatures and therefore BOTH keys. An attacker must defeat both
/// mechanisms.
/// Generated from manifest.schema.json#/$defs/custody_leg.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CustodyLeg {
    pub tier: Tier,
    /// Free text naming the concrete mechanism, e.g. "YubiHSM2 slot 3" or
    /// "age-encrypted file, offline laptop". Human-readable only.
    pub mechanism: String,
}

/// The lenient projection of [`CustodyLeg`].
///
/// Every field optional, every enum degraded to `String`. This is what a
/// VERIFIER parses, and the leniency is deliberate: reading five named
/// security fields fail-closed is field access, and a strict parse would
/// collapse every distinct refusal into one `Malformed`. It also means a
/// field no verifier reads cannot cause a refusal by being the wrong shape.
///
/// **Never make a decision on a `Raw*` value.** Promote it with `try_from`,
/// or read one named field and apply the check that governs it. The
/// fail-safe accessors live on the strict type only, so a `Raw*` cannot
/// answer a policy question at all.
#[derive(Debug, Clone, PartialEq, Eq, Default, Deserialize)]
pub struct RawCustodyLeg {
    pub tier: Option<String>,
    pub mechanism: Option<String>,
}

/// Maps each governable resource to its floor tier.
///
/// RK-1: a resource ABSENT from this file MUST be treated as T3. That rule
/// cannot be expressed in JSON Schema — a schema constrains what is present,
/// never what is missing — so it is carried instead by the `x-acp-absent`
/// annotation on `floors` below, which `tools/codegen.sh` reads to GENERATE
/// the fail-safe direction into `Tier::for_unclassified()` (crates/acp-core)
/// and its TypeScript equivalent. The Python reference spells the same
/// default at `acp_executor.py`. A conformance case asserts it, because a
/// fail-safe default that only exists in a comment is not a control — and
/// stating it only in this prose is what let the Rust and TypeScript versions
/// return HIGH, a RISK LEVEL, where a TIER was required.
///
/// RES-1 (A-7): the architecture guarantees no runtime component evaluates a
/// resource BELOW its signed floor. It cannot know whether the floor was set
/// correctly. A production database labelled T0 defeats the design with zero
/// attack. Floor maintenance is the highest-leverage governance task in the
/// system and is structurally unprovable — this file is where that risk
/// concentrates.
/// Generated from floors.schema.json.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Floors {
    pub schema_version: String,
    /// resource identifier -> floor tier. Deliberately an open map: resources are
    /// deployment-specific. The VALUES are closed.
    /// PRIVATE, deliberately. Reached through the accessor below, which
    /// carries the fail-safe absent rule the schema declares. A public
    /// map is a `.get()` away from an `Option` and an `Option` is one
    /// `unwrap_or` away from the permissive default.
    floors: BTreeMap<String, Tier>,
}

impl Floors {
    /// The only `schema_version` this build understands.
    pub const SCHEMA_VERSION: &'static str = "1";

    /// Look up one entry in `floors`.
    ///
    /// RK-1: absent means unknown, and unknown is the HIGHEST tier, not the
    /// lowest (P-4). Returning T0 or T1 here is the whole class of defect this
    /// specification exists to prevent, and it is the direction a lookup
    /// returning `Option` invites.
    ///
    /// Generated from the schema's `x-acp-absent` rule. It is not restated
    /// here, and editing it there changes this.
    pub fn get(&self, key: &str) -> Tier {
        let found = self.floors.get(key).copied();
        found.unwrap_or(Tier::T3)
    }

    /// Every entry, for callers that enumerate rather than look up — an
    /// auditor listing signed policy, not a decision path.
    pub fn entries(&self) -> impl Iterator<Item = (&String, &Tier)> {
        self.floors.iter()
    }
}

/// The lenient projection of [`Floors`].
///
/// Every field optional, every enum degraded to `String`. This is what a
/// VERIFIER parses, and the leniency is deliberate: reading five named
/// security fields fail-closed is field access, and a strict parse would
/// collapse every distinct refusal into one `Malformed`. It also means a
/// field no verifier reads cannot cause a refusal by being the wrong shape.
///
/// **Never make a decision on a `Raw*` value.** Promote it with `try_from`,
/// or read one named field and apply the check that governs it. The
/// fail-safe accessors live on the strict type only, so a `Raw*` cannot
/// answer a policy question at all.
#[derive(Debug, Clone, PartialEq, Eq, Default, Deserialize)]
pub struct RawFloors {
    pub schema_version: Option<String>,
    pub floors: Option<BTreeMap<String, String>>,
}

/// `Identity`.
/// Generated from manifest.schema.json#/$defs/identity.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Identity {
    /// Stable identifier. Compared byte-for-byte for PB-2; display_name is never
    /// used for the comparison because two people can share a display name.
    pub id: String,
    pub display_name: String,
}

/// The lenient projection of [`Identity`].
///
/// Every field optional, every enum degraded to `String`. This is what a
/// VERIFIER parses, and the leniency is deliberate: reading five named
/// security fields fail-closed is field access, and a strict parse would
/// collapse every distinct refusal into one `Malformed`. It also means a
/// field no verifier reads cannot cause a refusal by being the wrong shape.
///
/// **Never make a decision on a `Raw*` value.** Promote it with `try_from`,
/// or read one named field and apply the check that governs it. The
/// fail-safe accessors live on the strict type only, so a `Raw*` cannot
/// answer a policy question at all.
#[derive(Debug, Clone, PartialEq, Eq, Default, Deserialize)]
pub struct RawIdentity {
    pub id: Option<String>,
    pub display_name: Option<String>,
}

/// Identity and provenance of one signed policy bundle. PB-5: bundle_epoch is
/// strictly increasing and never reused or decreased. PB-2: author and
/// reviewer identities MUST differ — asserted by the signer, because a schema
/// cannot express a comparison between two of its own fields.
/// Generated from manifest.schema.json.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Manifest {
    /// Version of this manifest schema. Present so a decoder can refuse a bundle
    /// it does not fully understand rather than ignoring fields it does not
    /// recognise.
    pub schema_version: String,
    /// PB-5. Strictly increasing integer. Never reused, never decreased. The
    /// Executor keeps a high-water mark indefinitely (CL-4) — an expiring epoch
    /// mark would reopen rollback.
    pub bundle_epoch: u64,
    /// RFC 3339 UTC. Informational: freshness is enforced by expires_at and by
    /// the epoch, never by comparing this to a local clock.
    pub created_at: String,
    /// Who wrote this bundle. PB-2: MUST differ from reviewer.
    pub author: Identity,
    /// Who reviewed it. PB-2: MUST differ from author. Two-person integrity on
    /// the highest-leverage governance artifact in the system — RES-1 names floor
    /// maintenance as exactly that.
    pub reviewer: Identity,
    /// RFC 3339 UTC. PB-1: the engine MUST refuse to serve an expired bundle. A
    /// deployment MAY configure a grace window during which all Decisions are
    /// capped at ATTEST — it may not configure one that serves the bundle
    /// normally.
    pub expires_at: String,
    /// CR-4. The signed floor on signature suites. A receipt or attestation
    /// declaring a weaker suite is refused. This is in the signed bundle
    /// precisely so a downgrade cannot be negotiated at runtime.
    ///
    /// It is NOT this bundle's own floor. It floors the suites of downstream
    /// receipts and attestations; the floor THIS bundle must clear is configured
    /// out of band in the verifier, because a floor a bundle can lower is not a
    /// floor (RES-8). Wiring this field in as the bundle's own floor looks like
    /// an improvement and is the recurring defect.
    ///
    /// Drawn from `signature.schema.json` rather than restated, so that one edit
    /// to the suite list cannot leave the two spellings disagreeing.
    pub min_suite: SuiteId,
    pub custody: Custody,
}

impl Manifest {
    /// The only `schema_version` this build understands.
    pub const SCHEMA_VERSION: &'static str = "1";
}

/// The lenient projection of [`Manifest`].
///
/// Every field optional, every enum degraded to `String`. This is what a
/// VERIFIER parses, and the leniency is deliberate: reading five named
/// security fields fail-closed is field access, and a strict parse would
/// collapse every distinct refusal into one `Malformed`. It also means a
/// field no verifier reads cannot cause a refusal by being the wrong shape.
///
/// **Never make a decision on a `Raw*` value.** Promote it with `try_from`,
/// or read one named field and apply the check that governs it. The
/// fail-safe accessors live on the strict type only, so a `Raw*` cannot
/// answer a policy question at all.
#[derive(Debug, Clone, PartialEq, Eq, Default, Deserialize)]
pub struct RawManifest {
    pub schema_version: Option<String>,
    pub bundle_epoch: Option<u64>,
    pub created_at: Option<String>,
    pub author: Option<RawIdentity>,
    pub reviewer: Option<RawIdentity>,
    pub expires_at: Option<String>,
    pub min_suite: Option<String>,
    pub custody: Option<RawCustody>,
}

/// Maps each action class to the parties told when an IRREVERSIBLE action of
/// that class executes BELOW floor-HIGH.
///
/// WHY THIS FILE EXISTS. Risk is recomputed from the target resource's tier
/// floor; reversibility is a property of the action class. They are
/// orthogonal, so an action can be IRREVERSIBLE and LOW at the same time —
/// and every clause governing irreversible actions lived behind DR-1, which
/// scopes the deferred-release gate to floor-HIGH. Below HIGH the Executor
/// computed the reversibility class and discarded it: the action executed
/// with no notification, no acknowledgement, and no record that a human
/// existed. RV-1's fail-safe default set a value nothing on that path read.
/// Mail exfiltration is exactly this shape — floor an inbox at T1, which is
/// the natural choice because reading mail is routine, and an injected
/// send_email goes out unseen.
///
/// WHY THE RECIPIENTS ARE HERE AND NOT IN THE NOTIFIER'S CONFIGURATION. A
/// notification service that selects its own audience is certifying its own
/// coverage. That is RES-8 — a verifier must never accept a derived security
/// value from the party it is verifying — and it is the exact shape of the
/// still-open finding T-32, where note.source_path, note.from_canonical and
/// delivered are all classified T. Naming recipients in the signed bundle
/// puts the audience under RK-5 two-person offline control alongside the
/// floors it complements, and makes "who would have found out" a property an
/// auditor reads off signed policy rather than asks the notifier about.
///
/// ABSENCE FAILS CLOSED, AND JSON SCHEMA CANNOT SAY SO. An action class that
/// is IRREVERSIBLE, graded below HIGH, and absent from this file MUST cause
/// the Executor to refuse the action: a notice with no addressee is not a
/// detection channel, and DR-8's rule — executing while the detection channel
/// is absent is executing unwatched — does not become false because the risk
/// grade is lower. The condition spans three files (this one,
/// reversibility.json, and the risk grading over floors.json), so no schema
/// keyword can express it. The rule is normative in §9.6 DR-13 and its
/// enforcement point is the Executor, as with PB-7 in attesters.schema.json.
/// A normative rule with no enforcement point is a comment.
///
/// WHAT IS NOT REQUIRED: acknowledgement. DR-9's friction is affordable at
/// floor-HIGH because a human quorum has already been paid for. Below HIGH
/// there is no quorum and the traffic is the bulk of a deployment, so
/// demanding acknowledgement would page a human for routine work at volume —
/// T-26 habituation and AT-7 rubber-stamping, and W2 already recorded that
/// saturating approvers produces assent rather than refusal. DR-13 buys
/// detection, not prevention, and is stated as the weaker guarantee it is.
///
/// DELIVERY IS NOT A PRECONDITION OF EXECUTION. EO-2 budgets 25 ms p99
/// end-to-end for LOW and MEDIUM decisions and a synchronous confirmed
/// delivery does not fit inside it — two normative requirements that cannot
/// both hold, which is the DR-6 defect class. What DR-13 requires before
/// execution is the durable local commit of the notice. A notice committed
/// and never delivered leaves an audit record and no human; that residual is
/// disclosed as RES-P6, and reconciling committed notices against delivery
/// outcomes is a deployment obligation.
///
/// A-7 applies here as it does to floors and to reversibility: that a
/// deployment named the RIGHT recipients is conceded unprovable. Deployments
/// SHOULD floor action classes that are both irreversible and externally
/// visible at T2 or above, which moves them onto the deferred path under
/// DR-9; this file is what holds when they have not.
/// Generated from notice_targets.schema.json.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NoticeTargets {
    pub schema_version: String,
    /// action class -> recipient identities. Open map (actions are
    /// deployment-specific), and every value is a non-empty set. An empty array
    /// is REFUSED rather than treated as 'notify nobody': the two are
    /// indistinguishable at run time from an entry that was never written, and
    /// the fail-safe reading of both is refusal. Making the empty case invalid
    /// here means a deployment that wants no notice channel for a class must say
    /// so by floor policy — raise the class to T2+ and let DR-9 govern it —
    /// rather than by writing a control that looks configured and does nothing.
    /// PRIVATE, deliberately. Reached through the accessor below, which
    /// carries the fail-safe absent rule the schema declares. A public
    /// map is a `.get()` away from an `Option` and an `Option` is one
    /// `unwrap_or` away from the permissive default.
    notice_targets: BTreeMap<String, Vec<String>>,
}

impl NoticeTargets {
    /// The only `schema_version` this build understands.
    pub const SCHEMA_VERSION: &'static str = "1";

    /// Look up one entry in `notice_targets`.
    ///
    /// DR-13: a notice with no addressee is not a detection channel, and DR-8's
    /// rule — executing while the detection channel is absent is executing
    /// unwatched — does not become false because the risk grade is lower. This is
    /// the one absent-rule of the three that is NOT a default value: there is no
    /// fail-safe recipient to fall back to, so the fail-safe outcome is that the
    /// action does not run. A lookup returning `Option` here would let a caller
    /// write `unwrap_or_default()` and execute unwatched with an empty audience.
    ///
    /// Generated from the schema's `x-acp-absent` rule. It is not restated
    /// here, and editing it there changes this.
    pub fn get(&self, key: &str) -> Result<&Vec<String>, AbsentFromSignedPolicy> {
        self.notice_targets.get(key).ok_or(AbsentFromSignedPolicy {
            table: "notice_targets",
            clause: "DR-13",
            why: "a notice with no addressee is not a detection channel, and DR-8's rule — executing while the detection channel is absent is executing unwatched — does not become false because the risk grade is lower. This is the one absent-rule of the three that is NOT a default value: there is no fail-safe recipient to fall back to, so the fail-safe outcome is that the action does not run. A lookup returning `Option` here would let a caller write `unwrap_or_default()` and execute unwatched with an empty audience.",
        })
    }

    /// Every entry, for callers that enumerate rather than look up — an
    /// auditor listing signed policy, not a decision path.
    pub fn entries(&self) -> impl Iterator<Item = (&String, &Vec<String>)> {
        self.notice_targets.iter()
    }
}

/// The lenient projection of [`NoticeTargets`].
///
/// Every field optional, every enum degraded to `String`. This is what a
/// VERIFIER parses, and the leniency is deliberate: reading five named
/// security fields fail-closed is field access, and a strict parse would
/// collapse every distinct refusal into one `Malformed`. It also means a
/// field no verifier reads cannot cause a refusal by being the wrong shape.
///
/// **Never make a decision on a `Raw*` value.** Promote it with `try_from`,
/// or read one named field and apply the check that governs it. The
/// fail-safe accessors live on the strict type only, so a `Raw*` cannot
/// answer a policy question at all.
#[derive(Debug, Clone, PartialEq, Eq, Default, Deserialize)]
pub struct RawNoticeTargets {
    pub schema_version: Option<String>,
    pub notice_targets: Option<BTreeMap<String, Vec<String>>>,
}

/// `RaiseClause`.
/// Generated from risk_functions.schema.json#/$defs/raise_clause.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RaiseClause {
    /// An EL-1 expression. EL-1 is deliberately minimal, TOTAL (no expression can
    /// fail to evaluate, so there is no error path to fall open through) and
    /// monotone.
    ///
    /// PRECEDENCE IS NORMATIVE: `&&` binds tighter than `||`. That sentence
    /// exists because its absence WAS a defect — Z1, found by building two
    /// evaluators from the prose alone and running 10,000 differential cases
    /// until they disagreed. An implementation that leaves precedence to its host
    /// language reproduces the ambiguity.
    pub r#if: String,
    pub then: Risk,
}

/// The lenient projection of [`RaiseClause`].
///
/// Every field optional, every enum degraded to `String`. This is what a
/// VERIFIER parses, and the leniency is deliberate: reading five named
/// security fields fail-closed is field access, and a strict parse would
/// collapse every distinct refusal into one `Malformed`. It also means a
/// field no verifier reads cannot cause a refusal by being the wrong shape.
///
/// **Never make a decision on a `Raw*` value.** Promote it with `try_from`,
/// or read one named field and apply the check that governs it. The
/// fail-safe accessors live on the strict type only, so a `Raw*` cannot
/// answer a policy question at all.
#[derive(Debug, Clone, PartialEq, Eq, Default, Deserialize)]
pub struct RawRaiseClause {
    pub r#if: Option<String>,
    pub then: Option<String>,
}

/// Maps each action class to whether it can be undone.
///
/// RV-1: an action ABSENT from this file MUST be treated as IRREVERSIBLE. As
/// with floors, JSON Schema cannot express absence, so the rule is carried by
/// the `x-acp-absent` annotation below and GENERATED into the type: `impl
/// Default for Reversibility` returns `Irreversible` in crates/acp-core, and
/// the lookup on the table returns it directly, so a struct update, a
/// deserialisation gap, or an `Option` a caller unwraps cannot silently
/// produce the permissive value.
///
/// Why this matters more than it looks: reversibility selects the
/// acknowledgement regime. IRREVERSIBLE at floor-HIGH demands positive
/// acknowledgement from a non-operator (DR-9) — silence is not consent.
/// Getting this entry wrong in the permissive direction converts a held
/// action into a released one.
///
/// RV-3 is the reason the value is recomputed here and never read from a
/// receipt: a compromised issuer claiming REVERSIBLE otherwise obtains Silent
/// mode. Proven in reference/proofs/binding.dfy as
/// `RV3_TrustedModeAcceptsDowngrade`.
///
/// A-7 applies here exactly as it does to floors: that a classification is
/// HONEST is conceded unprovable.
/// Generated from reversibility.schema.json.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ReversibilityTable {
    pub schema_version: String,
    /// action class -> reversibility. Open map (actions are deployment-specific),
    /// closed values.
    /// PRIVATE, deliberately. Reached through the accessor below, which
    /// carries the fail-safe absent rule the schema declares. A public
    /// map is a `.get()` away from an `Option` and an `Option` is one
    /// `unwrap_or` away from the permissive default.
    reversibility: BTreeMap<String, Reversibility>,
}

impl ReversibilityTable {
    /// The only `schema_version` this build understands.
    pub const SCHEMA_VERSION: &'static str = "1";

    /// Look up one entry in `reversibility`.
    ///
    /// RV-1: reversibility selects the acknowledgement regime, so the permissive
    /// default converts a held action into a released one. An action nobody
    /// classified is one nobody thought about, and the fail-safe reading of that
    /// is that it cannot be undone.
    ///
    /// Generated from the schema's `x-acp-absent` rule. It is not restated
    /// here, and editing it there changes this.
    pub fn get(&self, key: &str) -> Reversibility {
        let found = self.reversibility.get(key).copied();
        found.unwrap_or(Reversibility::Irreversible)
    }

    /// Every entry, for callers that enumerate rather than look up — an
    /// auditor listing signed policy, not a decision path.
    pub fn entries(&self) -> impl Iterator<Item = (&String, &Reversibility)> {
        self.reversibility.iter()
    }
}

/// The lenient projection of [`ReversibilityTable`].
///
/// Every field optional, every enum degraded to `String`. This is what a
/// VERIFIER parses, and the leniency is deliberate: reading five named
/// security fields fail-closed is field access, and a strict parse would
/// collapse every distinct refusal into one `Malformed`. It also means a
/// field no verifier reads cannot cause a refusal by being the wrong shape.
///
/// **Never make a decision on a `Raw*` value.** Promote it with `try_from`,
/// or read one named field and apply the check that governs it. The
/// fail-safe accessors live on the strict type only, so a `Raw*` cannot
/// answer a policy question at all.
#[derive(Debug, Clone, PartialEq, Eq, Default, Deserialize)]
pub struct RawReversibilityTable {
    pub schema_version: Option<String>,
    pub reversibility: Option<BTreeMap<String, String>>,
}

/// `RiskFunction`.
/// Generated from risk_functions.schema.json#/$defs/risk_function.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RiskFunction {
    /// Action class this function grades. At most one function per action class —
    /// two functions for one class is an ambiguity, not a merge, and the loader
    /// refuses it.
    pub applies_to: String,
    pub base: Risk,
    /// Clauses evaluated in order. MONOTONE BY CONSTRUCTION: a clause can only
    /// raise the level, never lower it, which is why the field is `raise_to` and
    /// there is no `lower_to`. Monotonicity is what makes the Dafny proof that
    /// floors dominate raises tractable — a lowering clause would let a crafted
    /// parameter walk a HIGH action down to LOW.
    pub raise_to: Vec<RaiseClause>,
}

/// The lenient projection of [`RiskFunction`].
///
/// Every field optional, every enum degraded to `String`. This is what a
/// VERIFIER parses, and the leniency is deliberate: reading five named
/// security fields fail-closed is field access, and a strict parse would
/// collapse every distinct refusal into one `Malformed`. It also means a
/// field no verifier reads cannot cause a refusal by being the wrong shape.
///
/// **Never make a decision on a `Raw*` value.** Promote it with `try_from`,
/// or read one named field and apply the check that governs it. The
/// fail-safe accessors live on the strict type only, so a `Raw*` cannot
/// answer a policy question at all.
#[derive(Debug, Clone, PartialEq, Eq, Default, Deserialize)]
pub struct RawRiskFunction {
    pub applies_to: Option<String>,
    pub base: Option<String>,
    pub raise_to: Option<Vec<RawRaiseClause>>,
}

/// Deterministic functions from a Proposal's parameters and its targets'
/// effective tiers to a risk level.
///
/// RK-2 exists because static per-action risk is insufficient:
/// `modify_firewall_rule = HIGH` says nothing useful, since risk is a
/// function of PARAMETERS and TARGETS, not action names.
///
/// THE ABSENT CASE DIFFERS FROM floors AND reversibility. An action with no
/// risk function is REFUSED at §8.4 step 3 — it is NOT graded HIGH. Refusing
/// and grading-HIGH are different behaviours: grading HIGH would route an
/// unknown action into the human quorum, which looks conservative but
/// silently teaches approvers to rubber-stamp things the policy author never
/// considered. P-4: unknown is never LOW, and here it is not HIGH either — it
/// is a refusal.
///
/// TR-8: these functions are evaluated by the Executor over the INDEPENDENTLY
/// RECEIVED canonical Proposal and the trusted bundle, ignoring every
/// Context-Store raise and ignoring any risk value asserted in the receipt.
/// The recomputed value is what all subsequent attestation requirements key
/// on.
/// Generated from risk_functions.schema.json.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RiskFunctions {
    pub schema_version: String,
    /// PRIVATE, deliberately. Reached through the accessor below, which
    /// carries the fail-safe absent rule the schema declares. A public
    /// map is a `.get()` away from an `Option` and an `Option` is one
    /// `unwrap_or` away from the permissive default.
    risk_functions: Vec<RiskFunction>,
}

impl RiskFunctions {
    /// The only `schema_version` this build understands.
    pub const SCHEMA_VERSION: &'static str = "1";

    /// Look up one entry in `risk_functions`.
    ///
    /// 8.4-3: THE ABSENT CASE HERE IS NOT THE ABSENT CASE IN floors OR
    /// reversibility. An action with no risk function is REFUSED, not graded
    /// HIGH. Grading HIGH would route an unknown action into the human quorum,
    /// which looks conservative and is worse: it teaches approvers to
    /// rubber-stamp things the policy author never considered (T-26 habituation,
    /// AT-7). P-4 says unknown is never LOW; here it is not HIGH either. A lookup
    /// returning `Option` would let a caller reach for HIGH as the obvious safe
    /// default and get this exactly wrong.
    ///
    /// Generated from the schema's `x-acp-absent` rule. It is not restated
    /// here, and editing it there changes this.
    pub fn get(&self, applies_to: &str) -> Result<&RiskFunction, AbsentFromSignedPolicy> {
        self.risk_functions
            .iter()
            .find(|item| item.applies_to == applies_to)
            .ok_or(AbsentFromSignedPolicy {
            table: "risk_functions",
            clause: "8.4-3",
            why: "THE ABSENT CASE HERE IS NOT THE ABSENT CASE IN floors OR reversibility. An action with no risk function is REFUSED, not graded HIGH. Grading HIGH would route an unknown action into the human quorum, which looks conservative and is worse: it teaches approvers to rubber-stamp things the policy author never considered (T-26 habituation, AT-7). P-4 says unknown is never LOW; here it is not HIGH either. A lookup returning `Option` would let a caller reach for HIGH as the obvious safe default and get this exactly wrong.",
        })
    }

    /// Every entry, for callers that enumerate rather than look up — an
    /// auditor listing signed policy, not a decision path.
    pub fn entries(&self) -> impl Iterator<Item = &RiskFunction> {
        self.risk_functions.iter()
    }
}

/// The lenient projection of [`RiskFunctions`].
///
/// Every field optional, every enum degraded to `String`. This is what a
/// VERIFIER parses, and the leniency is deliberate: reading five named
/// security fields fail-closed is field access, and a strict parse would
/// collapse every distinct refusal into one `Malformed`. It also means a
/// field no verifier reads cannot cause a refusal by being the wrong shape.
///
/// **Never make a decision on a `Raw*` value.** Promote it with `try_from`,
/// or read one named field and apply the check that governs it. The
/// fail-safe accessors live on the strict type only, so a `Raw*` cannot
/// answer a policy question at all.
#[derive(Debug, Clone, PartialEq, Eq, Default, Deserialize)]
pub struct RawRiskFunctions {
    pub schema_version: Option<String>,
    pub risk_functions: Option<Vec<RawRiskFunction>>,
}

/// The `SIGNATURE` file at the bundle root: the declared suite, and one
/// signature value per primitive that suite requires, over SHA-256 of the
/// canonical bundle tree.
///
/// A CORRECTION IS RECORDED HERE. Until this revision this file was named
/// `bundle.schema.json` and described a *tree index* — `schema_version`, a
/// `members` array of path+digest pairs, and a `signature` object carrying
/// two fixed base64 fields named `classical` and `pq`. None of that artifact
/// exists. §8.2's file listing contains no index file; the covered set is
/// established by the CANONICAL WALK (`walk_bundle`, in both
/// implementations), which is what makes "the tree" a fact rather than a
/// convention. And PB-8, added in v1.3.15 when the offline signer turned the
/// format from a diagram into bytes, specifies the file as a suite plus ONE
/// VALUE PER PRIMITIVE — a map keyed by primitive name, hex-encoded — which
/// is not the fixed pair the old schema declared.
///
/// So the normative source held two descriptions of one object, and they
/// disagreed: the encoding-split defect arriving inside the document that
/// exists to prevent it. It survived because NOTHING READ THE SCHEMAS. They
/// were normative and unexecuted, and the first consumer — `tools/codegen.sh`
/// — found this on its first run. That is the same shape as `sim/bundle.py`
/// silently dropping three fields from a hash for several releases: a
/// load-bearing artifact with no gate line.
///
/// WHY THE MEMBERS INDEX IS NOT COMING BACK. The old rationale was real —
/// without an explicit list, a verifier that skipped a file and a signer that
/// included it compute different hashes and neither can tell which is wrong.
/// The adopted answer is to make the WALK normative rather than to ship a
/// list: it refuses symlinks, refuses unrecognised file types, and orders
/// byte-wise, so two conformant implementations enumerate the same set. A
/// committed index would be a second statement of the same fact, and this
/// file exists because of what happens to the second statement.
/// Generated from signature.schema.json.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SignatureEnvelope {
    /// The suite this signature was produced under. PB-8: it MUST be inside the
    /// tree hash. Outside it, an attacker relabels a hybrid bundle as classical,
    /// the verifier obligingly requires one primitive, and the CR-3 downgrade
    /// costs nothing.
    pub suite: SuiteId,
    /// primitive name -> signature value, lowercase hex.
    ///
    /// CR-3, CONJUNCTIVE: the values present MUST be exactly those the declared
    /// suite requires, and every one of them MUST verify. Not "at least": a value
    /// for a primitive the suite does not declare is as much a refusal as a
    /// missing one, because an `any`-shaped check lets an attacker strip the
    /// post-quantum leg, present a genuine classical signature, and be accepted.
    ///
    /// Hex rather than base64, matching what both implementations write.
    /// Per-primitive lengths (Ed25519 64 bytes, ML-DSA-65 3309) are asserted in
    /// code and not here: `parts` is keyed by primitive, so no single value
    /// pattern can express a length that depends on its own key.
    /// PRIVATE, deliberately. Reached through the accessor below, which
    /// carries the fail-safe absent rule the schema declares. A public
    /// map is a `.get()` away from an `Option` and an `Option` is one
    /// `unwrap_or` away from the permissive default.
    parts: BTreeMap<String, String>,
}

impl SignatureEnvelope {
    /// Look up one entry in `parts`.
    ///
    /// CR-3, PB-8: a primitive the declared suite requires and this file does not
    /// carry is a stripped leg, and a stripped leg is the downgrade the hybrid
    /// suite exists to prevent. Absent is refused, never treated as 'not
    /// applicable'.
    ///
    /// Generated from the schema's `x-acp-absent` rule. It is not restated
    /// here, and editing it there changes this.
    pub fn get(&self, key: &str) -> Result<&String, AbsentFromSignedPolicy> {
        self.parts.get(key).ok_or(AbsentFromSignedPolicy {
            table: "parts",
            clause: "CR-3, PB-8",
            why: "a primitive the declared suite requires and this file does not carry is a stripped leg, and a stripped leg is the downgrade the hybrid suite exists to prevent. Absent is refused, never treated as 'not applicable'.",
        })
    }

    /// Every entry, for callers that enumerate rather than look up — an
    /// auditor listing signed policy, not a decision path.
    pub fn entries(&self) -> impl Iterator<Item = (&String, &String)> {
        self.parts.iter()
    }
}

/// The lenient projection of [`SignatureEnvelope`].
///
/// Every field optional, every enum degraded to `String`. This is what a
/// VERIFIER parses, and the leniency is deliberate: reading five named
/// security fields fail-closed is field access, and a strict parse would
/// collapse every distinct refusal into one `Malformed`. It also means a
/// field no verifier reads cannot cause a refusal by being the wrong shape.
///
/// **Never make a decision on a `Raw*` value.** Promote it with `try_from`,
/// or read one named field and apply the check that governs it. The
/// fail-safe accessors live on the strict type only, so a `Raw*` cannot
/// answer a policy question at all.
#[derive(Debug, Clone, PartialEq, Eq, Default, Deserialize)]
pub struct RawSignatureEnvelope {
    pub suite: Option<String>,
    pub parts: Option<BTreeMap<String, String>>,
}
