#!/usr/bin/env python3
"""Emit the cross-language primitive fixture that crates/acp-crypto verifies.

Python signs; Rust verifies. The fixture is committed so `cargo test` needs no
Python, which means it can silently stop describing the code — so the generator
lives here, beside the thing it generates, and `--check` asserts the committed
file still replays.

Run after any change to key derivation or the signed-message construction:

    python3 tools/gen-crypto-vectors.py            # rewrite the fixture
    python3 tools/gen-crypto-vectors.py --check    # verify it is current

`--check` regenerates the deterministic FIELDS ONLY. It cannot compare
signatures byte-for-byte: ML-DSA signing is hedged, so `ML_DSA_65.sign` returns
a different valid signature every call. Keys and the fingerprint are derived
from a seed and ARE stable, so those are compared; the signatures are instead
re-verified with the Python verifier. A drifted fixture therefore shows up as a
key mismatch, which is the case that actually breaks the Rust test.
"""
import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "reference" / "src"))

from acp_crypto import HybridKey  # noqa: E402
from cryptography.hazmat.primitives import serialization as ser  # noqa: E402
from dilithium_py.ml_dsa import ML_DSA_65  # noqa: E402

OUT = REPO / "crates" / "acp-crypto" / "tests" / "vectors" / "python_signatures.json"

# The seeds the Python suites already use as fixture identities. Keeping them
# the same means a divergence here is a divergence in the same key material the
# conformance suite signs with, not in a parallel set nobody else touches.
SEEDS = (b"k1", b"k2", b"kop")

MESSAGE = (b"ACP cross-language primitive vector: the Rust verifier must accept "
           b"what the Python signer produced.")


def build() -> dict:
    keys = []
    for seed in SEEDS:
        k = HybridKey(seed)
        ed_pk = k.ed_sk.public_key().public_bytes(
            ser.Encoding.Raw, ser.PublicFormat.Raw)
        ml_sig = ML_DSA_65.sign(k.ml_sk, MESSAGE)
        # Never emit a signature this process cannot itself verify: a fixture
        # that is wrong at birth would be read as a Rust defect.
        assert ML_DSA_65.verify(k.ml_pk, MESSAGE, ml_sig), "ML-DSA self-check failed"
        keys.append({
            "seed_utf8": seed.decode(),
            "fingerprint": k.public().fingerprint(),
            "ed25519_pk_hex": ed_pk.hex(),
            "ed25519_sig_hex": k.ed_sk.sign(MESSAGE).hex(),
            "mldsa65_pk_hex": k.ml_pk.hex(),
            "mldsa65_sig_hex": ml_sig.hex(),
        })
    return {
        "note": ("Generated by tools/gen-crypto-vectors.py from "
                 "reference/src/acp_crypto.py. Ed25519 via `cryptography` "
                 "(RFC 8032), ML-DSA-65 via `dilithium-py` (FIPS 204). "
                 "Verified in Rust by crates/acp-crypto/tests/python_interop.rs."),
        "message_utf8": MESSAGE.decode(),
        "keys": keys,
    }


def check() -> int:
    if not OUT.exists():
        print(f"FAIL  {OUT} does not exist")
        return 1
    have = json.loads(OUT.read_text())
    want = build()
    bad = 0

    if have.get("message_utf8") != want["message_utf8"]:
        print("FAIL  the signed message has changed; every signature is stale")
        bad += 1

    have_keys = {k["seed_utf8"]: k for k in have.get("keys", [])}
    for w in want["keys"]:
        h = have_keys.get(w["seed_utf8"])
        if h is None:
            print(f"FAIL  seed {w['seed_utf8']!r} is missing from the fixture")
            bad += 1
            continue
        # Seed-derived and therefore stable across processes and machines.
        for field in ("fingerprint", "ed25519_pk_hex", "mldsa65_pk_hex"):
            if h.get(field) != w[field]:
                print(f"FAIL  {w['seed_utf8']}: {field} drifted")
                bad += 1
        # Hedged, so compared by verification rather than by bytes.
        msg = want["message_utf8"].encode()
        if not ML_DSA_65.verify(bytes.fromhex(h["mldsa65_pk_hex"]), msg,
                                bytes.fromhex(h["mldsa65_sig_hex"])):
            print(f"FAIL  {w['seed_utf8']}: committed ML-DSA signature does not verify")
            bad += 1

    print("fixture is current" if not bad else f"{bad} problem(s)")
    return 1 if bad else 0


if __name__ == "__main__":
    if "--check" in sys.argv:
        sys.exit(check())
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(build(), indent=1) + "\n")
    print(f"wrote {OUT.relative_to(REPO)}")
