#!/usr/bin/env bash
# sign-release.sh — regenerate MANIFEST.sha256 and sign it with the OFFLINE
# release key. Run on the signing host, not on a build server.
#
# The private key is never generated by tooling that touched the dossier and
# never lives in this repository. RK-5 discipline applies to the release key
# for the same reason it applies to the policy bundle: a signature is only
# worth the custody of the key behind it.
#
#   ./sign-release.sh keygen             # once, on the offline host
#   ./sign-release.sh sign  ~/acp.key  # regenerate manifest + sign
set -euo pipefail
cd "$(dirname "$0")/.."   # tools/ -> repo root; the manifest covers paths from here

# Coverage is three allowlists and no deny-list. Each axis independently
# refuses to admit something unrecognised:
#
#   1. roots     -- only these directories are eligible at all
#   2. tracked   -- only files git tracks; build outputs are excluded because
#                   they are gitignored, not because a list names them
#   3. extension -- only these types, plus explicit filenames
#
# A deny-list fails open: the next thing someone adds is covered by default.
# That is how the previous blanket `find .` would have swept private/ and a
# stray .venv into a public manifest, publishing their filenames and hashes.
#
# Every root of the polyglot layout. Adding one is deliberate; a root that is
# not named here is not signed, which is the intended default. assert_roots_
# present fails loudly if one is missing, so a typo cannot silently sign less.
ROOTS="spec dossier reference crates packages sim deploy tools"
# html is here for sim/attacks/supplier_qc_report.html -- the poisoned supplier
# report whose payload is white-on-white hidden text. Its exact bytes ARE the
# evidence, so it is one of the files most in need of a signature. The previous
# extension allowlist would have skipped it silently while the manifest still
# looked complete; the halt-assertion is what surfaced it.
EXTS="md py rs ts json cddl dfy toml yml yaml lock txt sh pub html"
NAMED="LICENSE Dockerfile .gitignore"

covered_files() {
  # Universe: every tracked file at the repository root, plus every tracked
  # file under a signed root directory. Enumerating root files by name was
  # tried and rejected -- it silently dropped the eleven numbered dossier
  # documents and both tools. Depth-1 plus an extension allowlist keeps the
  # fail-safe property without a list that rots every time a document is added.
  { git ls-files | grep -v '/'
    for r in $ROOTS; do
      if [ -d "$r" ]; then git ls-files -- "$r"; fi
    done
  } | grep -vE '^MANIFEST\.sha256(\.sig)?$' | sort -u
}

# Halt if any covered file has a type we do not recognise. A new file type must
# stop the release, not be silently signed and not be silently skipped.
assert_all_recognised() {
  bad=""
  for f in $(covered_files); do
    base=${f##*/}
    ext=""
    case "$base" in *.*) ext=${base##*.} ;; esac
    case " $NAMED " in *" $base "*) continue ;; esac
    case " $EXTS " in *" $ext "*) continue ;; esac
    bad="$bad $f"
  done
  if [ -n "$bad" ]; then
    echo "unrecognised file type under a signed root:" >&2
    for f in $bad; do echo "    $f" >&2; done
    echo "  add its extension to EXTS, or its name to NAMED, or exclude it." >&2
    exit 4
  fi
}

assert_roots_present() {
  for r in $ROOTS; do
    [ -d "$r" ] || { echo "missing signed root: $r" >&2; exit 3; }
  done
}

case "${1:-}" in
keygen)
  # ACP-16. This used to hardcode ~/acp-release.key and then print "move to
  # offline media" -- so the tool itself created the exposure the dossier's
  # two-gate argument denies. A key in $HOME is readable by anything running as
  # that user: every npm install, every editor extension, every agent session
  # with shell access. The path is now REQUIRED and never defaults to $HOME.
  KEY="${2:?usage: $0 keygen /path/to/offline-media/acp-release.key}"
  # Refusing to overwrite is the discipline `sign` already applies to the
  # manifest, and it matters more here. A clobbered manifest can be re-signed;
  # a destroyed release key cannot be recovered, and every signature it ever
  # produced becomes permanently unverifiable. This ran with no guard and no
  # test for the whole life of the script.
  if [ -e "$KEY" ]; then
    printf 'refusing to overwrite an existing key: %s\n' "$KEY" >&2
    printf 'a destroyed release key cannot be recovered, and every signature\n' >&2
    printf 'it produced becomes unverifiable. Move or remove it first.\n' >&2
    exit 3
  fi
  python3 - "$KEY" <<'PY'
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives import serialization as ser
import getpass, hashlib, os, sys

# ACP-16. The key is encrypted AT REST, and that -- not its directory -- is what
# closes this. An unencrypted PEM is usable by any process running as this user
# wherever it sits; removable media only protects it while unplugged, which is
# every moment except the one where it is actually used. Encrypted, the file is
# inert without the passphrase and the plaintext key exists only in memory, for
# the seconds it signs.
def ask(prompt):
    # NOT sys.stdin.isatty(). getpass reads from /dev/tty, so a passphrase can
    # be typed even when stdin is a pipe -- which is how an agent harness, a
    # `cmd < /dev/null` and most CI wrappers invoke this. Gating on stdin
    # refused a perfectly interactive user; gating on the failure of the read
    # itself is the honest test. EOFError is getpass falling back to a stdin
    # with nothing on it; OSError is no controlling terminal at all.
    try:
        return getpass.getpass(prompt)
    except (EOFError, OSError):
        sys.exit("no terminal available to read a passphrase -- run this from "
                 "a real terminal. keygen will not generate an unencrypted key.")

pw = ask("passphrase for the new release key: ")
if len(pw) < 12:
    sys.exit("passphrase too short (12 characters minimum)")
if pw != ask("confirm passphrase: "):
    sys.exit("passphrases differ -- nothing written")

sk = Ed25519PrivateKey.generate()
priv = sk.private_bytes(ser.Encoding.PEM, ser.PrivateFormat.PKCS8,
                        ser.BestAvailableEncryption(pw.encode()))
pub = sk.public_key().public_bytes(ser.Encoding.PEM,
                                   ser.PublicFormat.SubjectPublicKeyInfo)
path = sys.argv[1]
with open(path, "wb") as f: f.write(priv)
os.chmod(path, 0o600)
open("release-key.pub", "wb").write(pub)
raw = sk.public_key().public_bytes(ser.Encoding.Raw, ser.PublicFormat.Raw)
print(f"private key : {path}  (chmod 600, passphrase-encrypted)")
print(f"public key  : release-key.pub  (ships with the dossier)")
print(f"fingerprint : SHA256:{hashlib.sha256(raw).hexdigest()[:32]}")
print("\nPublish that fingerprint out of band -- on the repository README, in\n"
      "the talk, in the review brief. A public key shipped only inside the\n"
      "package it authenticates proves nothing.")
print("\nStore the passphrase in a password manager you actually back up. The\n"
      "key is inert without it, and no copy of it exists anywhere else -- lose\n"
      "it and every signature this key produces becomes unreproducible.")
PY
  ;;
list)
  # What `sign` would cover, without needing the offline key. This is what
  # makes the coverage model testable at all: selftest.sh runs it, sign does not.
  assert_roots_present
  assert_all_recognised
  covered_files
  ;;

sign)
  KEY="${2:?usage: ./sign-release.sh sign /path/to/acp-release.key}"
  [ -f "$KEY" ] || { echo "no such key file: $KEY" >&2; exit 5; }
  assert_roots_present
  assert_all_recognised
  # Build and sign into temporaries, then move into place only once the
  # signature exists. Writing MANIFEST.sha256 first -- as this script used to --
  # meant a mistyped key path destroyed the only manifest whose signature still
  # verified, and nobody but the offline key holder could rebuild it. Failing
  # here must leave the previous release intact.
  trap 'rm -f MANIFEST.sha256.tmp MANIFEST.sha256.sig.tmp' EXIT
  covered_files | xargs sha256sum > MANIFEST.sha256.tmp
  python3 - "$KEY" <<'PY'
import getpass, sys
from cryptography.hazmat.primitives.serialization import load_pem_private_key

data = open(sys.argv[1], "rb").read()
try:
    # Unencrypted keys still load, so a pre-ACP-16 key keeps working and the
    # rotation is not forced by the tooling breaking.
    sk = load_pem_private_key(data, password=None)
except TypeError:
    # TypeError means "encrypted, no password given" -- distinct from the
    # ValueError an unparseable file raises, which must keep failing WITHOUT a
    # prompt. Prompting is TTY-only: selftest drives this path with a bogus key
    # and a prompt in a non-interactive context hangs forever instead of
    # failing. A gate that hangs is worse than a gate that fails.
    # Same reasoning as keygen: ask the terminal, not stdin. Failing the read
    # is what proves there is nowhere to type, and it must FAIL rather than
    # block -- a prompt reached from selftest or CI hangs forever, and a gate
    # that hangs reports nothing at all.
    try:
        pw = getpass.getpass(f"passphrase for {sys.argv[1]}: ")
    except (EOFError, OSError):
        sys.exit("key is passphrase-encrypted and there is no terminal to "
                 "read the passphrase from")
    try:
        sk = load_pem_private_key(data, password=pw.encode())
    except ValueError:
        # A wrong passphrase is the ONE failure here a user will actually hit,
        # and it was reporting itself as two stacked tracebacks -- the TypeError
        # from the password=None probe above, chained to a ValueError from the
        # retry. That reads like a crash in the signer rather than a typo, on
        # the one command whose output has to be unambiguous. `from None` breaks
        # the chain so the probe is not shown as an error; it is control flow.
        raise SystemExit(
            f"incorrect passphrase for {sys.argv[1]} — nothing was written, "
            "and the previous manifest and signature are untouched.") from None
open("MANIFEST.sha256.sig.tmp", "wb").write(
    sk.sign(open("MANIFEST.sha256.tmp", "rb").read()))
PY
  mv MANIFEST.sha256.tmp MANIFEST.sha256
  mv MANIFEST.sha256.sig.tmp MANIFEST.sha256.sig
  trap - EXIT
  echo "signed -> MANIFEST.sha256.sig"
  echo "files covered: $(wc -l < MANIFEST.sha256)"
  ;;
*)
  echo "usage: $0 {keygen <keyfile>|sign <keyfile>}"; exit 2 ;;
esac
